### ISSUE TITLE
Firefox - unresponsive script

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#100]

**Comment by LenkaDamborska** [comment]
Prosím o brzké vyřešení problému. Všem to padá (někdo musí i restartovat počítač) a pak nikdo neposílá připomínky, protože ho nenapadne to otevřít v jiném prohlížeči.

**Comment by honza-rychtar** [comment]
Mate feedback od lidi kterym to padalo, jestli uz je verze 0.1.1 ok?
Zatim mam potvrzeno ze 3 zdroju, ze v nove verzi uz to nepada.

**Comment by LenkaDamborska** [comment]
No vidíš, nemáme. Poptám se.
