### ISSUE TITLE
Prepnuti vyhledavani podle ...

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#102]
"""Když něco napíšu do vyhledávacího okna a potom napravo změním, podle čeho mi to má vyhledávat (Název, Autor, Klíčové slovo, ...), zmizí mi to, co jsem napsala. Čekala bych, že se mi podle toho změní vyhledávání."""

**Comment by honza-rychtar** [comment]
Vyhledavaci pole asi predelam, aby se vyhledavalo pouze ve vsem.
Hledani pres klicova slova, autory, .. bude mozne az v obrazovce hledani - kde bude spousta filtru a kriterii, vcetne tech co jsou ted nahore v toolbaru.

**Comment by LenkaDamborska** [comment]
V tom případě jo. Pro nás knihovníky je těžké přijít o pokročilé vyhledávání, ale rozumím tomu, že uživatelé jdou většinou přes jedno okno.

**Comment by honza-rychtar** [comment]
Viz #137
