### ISSUE TITLE
Vybrané - náhledy na úvodní stránce

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#103]
"""Vybrané - náhledy na úvodní stránce by měly být na celé stránce, teď je dole nehezká mezera (když se zvětšuje rozlišení a není tam dost titulů)"""

**Comment by honza-rychtar** [comment]
A co tam chcete dat? Nektere knihovny namaji dostatek titulu a uz vubec nemaji dost vybranych.

**Comment by LenkaDamborska** [comment]
Nevím. Taky jsem se ptala.. Za MZK se klidně může přidat víc titulů, ne? Ta mezera tam vznikne při větším rozlišení. Já jsem si toho při svém nevšimla. Možná na to můžou knihovny pamatovat, že vznikne nehezká mezera, takže tam přidají tituly.
