### ISSUE TITLE
Procházet - třídění by mohlo být abecedně (u procházení dle jmen autorů a klíčových slov)

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#105]

**Comment by honza-rychtar** [comment]
Dal bych to jako volbu, ale defaultne bych nechal podle vyskytu. Klicovych slov je spousta, pri prochazeni me zajimaji hlavne ty, ktere jsou pouzvana vicekrat. Pokud by to bylo podle abecedy, tak nez projedu vsechna zazinajici na "A" s jednim nebo dvema vyskyty, tak me to prestane bavit.

Pokud naopak hledam konkretni klicove slovo, tak k tomu slouzi vyhledavani, ne prochazeni.

**Comment by LenkaDamborska** [comment]
Myslíš jako volbu přímo v konkrétním panelu v procházení? Mohlo by tam být něco jako Řadit dle výskytu/abecedně.
