### ISSUE TITLE
Prochazeni PDF dokumentu

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#106]
"""Nejsou pro čtenáře matoucí v Procházet PDF dokumenty? Jak se z pohledu čtenáře liší pdf dokumenty od ostatních? Jen formátem, nebo i typem obsahu? Upřesnit název sbírky nebo popsat její obsah?"""

**Comment by honza-rychtar** [comment]
Popravde to je jako samostatna kategorie jen kvuli testovacim ucelum.

"Jak se z pohledu čtenáře liší pdf dokumenty od ostatních?"
 No tak zejmena to nejsou digitalizovane dokumenty - jen se vzalo PDF (puvodne uz digitalni), doplnila se zakladni metadata a hotovo. To uz tam rovnou muzem davat spreadsheety, fotky porizene telefonem nebo videa. Z meho pohledu se tam takove dokumenty moc nehodi. Ale chapu, ze je tam chcete a muze to mit i zajimavy use case, napr. diplomove prace v Krameriovi univerzit.

A taky se podivejte jak K4 klient pracuje s PDF dokumenty - otevre cele PDF v novem tabu, tedy klient se uplne opusti a pak zalezi na pouzivanem prohlizeci jak se PDF dokumenty zobrazi - takze z pohledu ctenaru se opravdu pdf dokumenty lisi.
PDF dokumenty taky nemaji nahledy stranek.

Ve svem klientovi se snazim rozdily ve formatech z pohledu uzivatele odstinit - PDF dokument se otevre stejne jako jiny dokument, zobrazi se stejna metadata, neutikam z klienta, mam integrovany prohlizec pdf a jen schovam panel s nahledy, protoze nejsou k dispozici. Ted jsem si vsimnul, ze u pdf dokumentu tam je jeste stary panel s ovladacima prvkama - to zmenim.

Kategorii prochazeni podle PDF dokumentu pozdeji odstranim.
Pro odliseni PDF dokumentu jsem nekdy v predchozich verzich pridal "tag" PDF na karty. Takze v novinkach, vysledcich hledani apod. je primo videt, ze se jedna o PDF dokument.

**Comment by LenkaDamborska** [comment]
Ten štítek PDF na kartě mi přijde fajn. Taky bych tu kategorii procházení PDF dokumenty zrušila. Jinak my tak např. archivujeme a zveřejňujeme obsah CD v MZK. Vše, co je na CD, se uloží v archivu, a co jde zpřístupnit, se nahraje do Krameria. Většinou jsou to PDF. Taky občas dostaneme nějaké e-knihy od neziskovek a dáváme je do Krameria. Takže tam máme jak digitalizované dokumenty, tak i born digital a má to svůj význam.. Ale nějak speciálně vyčleňovat se nemusí.
