### ISSUE TITLE
Nakladatelské údaje v metadatech

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#110]
"""Nakladatelské údaje v metadatech - co to ještě vymyslet jinak? Je tam Datum: a Místo:, ale není tam Název nakladatele nebo jen Název.. To by bylo ale zase dlouhé. Co to dát bez těch popisků a seřadit pod sebou v pořadí místo - název - rok? Např.:
Praha
Družstevní práce
1947"""

**Comment by zabak** [comment]
Z MARCu bys bral celé pole 260/264 tak jak je. Zapiš to na jeden řádek Praha: Družstevní práce, 1947

**Comment by honza-rychtar** [comment]
Ok, rozepsane je to pak v dialogu s podrobnostma o vydavatelich  (a autorech), ktery se zobrazi po kliku na "Nakladatelske udaje" (nebo "Autor").
To pak musim udelat nejak, ze jde videt, ze se info da rozkliknout.

**Comment by LenkaDamborska** [comment]
Jsem pro přebrat pole 260 nebo 264 tak, jak je. To bude i lepší, než to mít pod sebou.
