### ISSUE TITLE
Přepínátko Veřejné/neveřejné

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#112]
Při použití přepínače Pouze veřejné z prava do leva (z modré do bílé) by se mělo objevit Veřejné i neveřejné.

**Comment by LenkaDamborska** [comment]
Další názor na stejné téma: "Nevim, zda bude koncovym uzivatelum dostatecne srozumitelne "udelatko" pro "Pouze verejne" a práce s nim ve stavajici podobe."

**Comment by honza-rychtar** [comment]
Prepinatko se zrusi
Viz #137
