### ISSUE TITLE
Prohlížečka - fullscreen

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#116]
Zapnout/vypnout fullscreen - přejmenování na "zobrazit na plnou obrazovku" nebo něco v tom smyslu

**Comment by honza-rychtar** [comment]
Fullscreen bych predelal na komplet fullscreen, viz #127 
V Chromu se to jmenuje "Rezim cele obrazovky", tak mozna to pojmenovat stejne.
