### ISSUE TITLE
Vyhledávání

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#121]
"Vyhledavaci pole opticky splyva s okolím webovske stranky - doporucuji barevne odlisit, napr. zesvetlat - bila nebo seda, nebo zvýraznit modry obrys."

**Comment by honza-rychtar** [comment]
No nevim, je to na kazde strance, tak at to nerusi (bila na tmavem by byla hodne rusiva).
Navic ted je vyhledavaci pole prakticky pres cely toolbar, to bych musel byt slepy, abych si toho nevsimnul. Je tam i lupa a text "Hledat v digitalni knihovne". 

Barvu bych zmenil jen pokud na vyhledavaci pole najedu kurzorem mysi - coz me vizualne navede, ze je pole interaktivni.

To ze pole splyva s okolim neni bug ale ficura :) 
Poku by uzivatele meli caste pripominky, ze v apikaci nenasli hledani, tak bych to zmenil.

**Comment by LenkaDamborska** [comment]
Co to aspoň zkusit zvýraznit modře? :) Hůře vidící s tím můžou mít problém.

**Comment by zabak** [comment]
Testoval jsem to pomocí aplikace Colour Contrast Analyzer. Zatímco bílé texty jsou OK a šedší nadpisy metadat jsou na hranici, tak toto nevyhovuje. Ale na druhou stranu vidět to je - ve smyslu, že to nejsou dvě barvy, které by si mohli zaměnit barvoslepí. V každém případě toto navrhuji zavřít a může se to stát součástí budoucích vylepšení v rámci #74.
