### ISSUE TITLE
Náznak, že se něco děje

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#122]
"Pokud systém pracuje, napr. hleda nebo generuje vystup, není to vzdy vizualne patrne. Stalo se mi to několikrát při ruznych krocich.
Koncovi uzivatele jsou obvykle netrpelivi a chteji všechno nejlepe ihned. Budou se domnívat, ze systém nic nenasel nebo spadnul a odejdou. Hlaseni "hledam" se objevi az po zasahu ve vyhledavacim poli, mělo by byt opticky zretelne hned od zacatku, kdy systém pracuje na zaklade určitého prikazu. Obavam se, ze si u generovani vystupu v PDF většina uzivatelu vůbec nevsimne upozorneni na moznost delšího trvani."

**Comment by LenkaDamborska** [comment]
"Po kliknutí na "Generovat" (které bychom možná mohli přejmenovat na "vytvořit"?) nejde vůbec poznat, že se něco děje."

**Comment by honza-rychtar** [comment]
Pokud jde o generovani PDF, tak viz #114 
Vsude jinde je znazorneny prubeh nacitani tocicim koleckem uprostred obrazovky (jeho vzhled zmenim).

"Hlaseni "hledam" se objevi az po zasahu ve vyhledavacim poli, mělo by byt opticky zretelne hned od zacatku, kdy systém pracuje na zaklade určitého prikazu."

- To moc nechapu. Ano, hlaseni "Vyhledavam" se objevi, az zacnu zadavat text ve vyhledavacim poli - kdy jindy by se mel objevit? Jeste pred tim, nez zacnu hledat :)
Kdyz zadavam text, tak se vypise "Vyhledavam", hned na to se zacnou zobrazovat doporucene vysledky pres naseptavac a jakmile hledani odpalim, tak se nacitani znazorni tocicim koleckem. 
Nevim co vic by se v tom dalo vymyslet.

**Comment by LenkaDamborska** [comment]
Upřímně už nevím, jak to daná osoba myslela.. Možná to měla zpožděné :) Fakt hned od začátku jde poznat, že se něco děje, tak tohle klidně můžeš uzavřít.
