### ISSUE TITLE
Kombinované vyhledávání

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#123]
"Povazuji za podstatny nedostatek systemu:
Při vyhledavani v resersni masce nelze kombinovat udaje z ruznych poli při volbe "Vse", napr. prijmeni autora a slovo z nazvu, coz uzivatele budou nezridka zadavat. Zkousela jsem napr. zadat Čapek čtení a Uprka Kožuchy. V obou těchto pripadech byl výsledek nulovy."

**Comment by honza-rychtar** [comment]
Viz #137
