### ISSUE TITLE
Booleovský operátor

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#124]
"Navrhovane rozhrani neumoznuje na rozdil od vetsiny soucasnych vyhledavacich systemu pouziti booleovských operatoru ani znaku pro rozsireni."

**Comment by honza-rychtar** [comment]
Viz #137 

AND/OR operatory budou ve vyznamu AND mezi kategoriemi filtru a OR mezi polozkami v jedne kategorii.

Otazka je jestli povolit menit tenhle implicitni vyznam.
Pouziti AND uvnitr kategorie me napada u autoru - nalezeni dokumentu, na kterych se podilel rytec X a kartograf Y.
Kategorie jako je typ dokumentu maji navzajem disjunktni polozky, takze tam AND nedava smysl.
Priklad pouziti OR mezi kategoriemi me zadne nenapada.

Obecne je slozite (mozna nemozne) vytvorit system zanorenych AND/OR/NOT pres GUI (ne ve smyslu implementace, ale navrhnout to pochopitelne pro uzivatele) - spis to uzivatele mate a stejne tomu moc nerozumi. 
Treba pokrocile vyhledavani ve VuFindu je i pro me celkem neprehledne - https://vufind.mzk.cz/Search/Advanced# - vidim tam, ze se daji tvorit skupiny a uvnitr nich se da vybrat OR nebo AND a pak se da vybrat OR/AND na vsechny skupiny (relace mezi nemi) - ale neda se kombinovat. Operator se aplikuje na vsechny kategorie.

Ja vim, ze je to korektni a uplny system, protoze kazdy vyrok se da prevest do disjuktni normalni formy a pouzitim OR na skupiny a AND uvnitr skupin mi da moznost vyhledat libovolny vyrok.
Ale kolik uzivatelu VuFindu ma trosicku pokrocilejsi zaklady vyrokove logiky? :)

Kazdopadne by se mohlo u kazde kategorie pridat prepinatko na OR/AND (nejak at to uzivatele nemate), s tim ze by bylo defaultne OR a u typu dokumentu by nebylo vubec.

**Comment by LenkaDamborska** [comment]
Toto je opravdu na diskuzi. Já bych tím uživatele nezatěžovala.

**Comment by zabak** [comment]
Navrhuji toto zavřít, myslím, že toto řeší #137 a zůstalo to otevřené spíš omylem. Pokud vznikne požadavek na GUI pro pokročilé hledání, tak by si to zasloužilo samostatné issue.
