### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#127]
"Nefunguje zobrazení fullscreenu - když na něj kliknu, tak mi akorát zmizí obě postranní nabídky a velikost stránky se nijak nezmění."

**Comment by honza-rychtar** [comment]
To neni chyba, bylo to tak zamysleno.
Ale asi to udelam tak, ze nahledy a metadata se budou schovavat zvlast a fullscreen v prohlizecce bude uplny fullscreen prohlizecky, tj. schova se i okno browseru.

**Comment by honza-rychtar** [comment]
Hotovo, viz #162
