### ISSUE TITLE
Textový seznam položek

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#129]
Nebo možná lépe "textové zobrazení".

"U některých dokumentů by se hodila:
- možnost přepnout zobrazení dokumentů na textovou podobu bez náhledu  - hlavně u těch periodik, např. u Lidových novin, mně celkem dlouho trvalo než se mi zobrazila poslední čísla (nebo případně přidat nějaký kalendář s jednotlivými čísly?),
- a stejně tak nabídnout textovou verzi i u náhledů stránek."

**Comment by LenkaDamborska** [comment]
Např. ve Vufindu je při prohlížení výsledků vyhledávání možnost "Přepnout na tabulku".

**Comment by zabak** [comment]
Toto je myslím dostatečně vyřešeno pro periodika, u stránek bych řešil spíše #275. Navrhuji zavřít.

**Comment by honza-rychtar** [comment]
@zabak Ano, Zaviram.
