### ISSUE TITLE
Hlavní menu

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#132]
"Menu na levé straně:
"Doporučené" – startovní stránka: není mi jasné, kým, pro koho a za jakým účelem jsou zde vystavené dokumenty doporučené...
"Procházet" – domnívám se, že by naopak tato možnost měla být nějak zvýrazněna (když už musí být startovní stránkou Doporučené) – jako počátek seriózní vědecké práce s digitalizovanými dokumenty."

**Comment by honza-rychtar** [comment]
viz #130 
"jako počátek seriózní vědecké práce s digitalizovanými dokumenty"
Doporucene si knihovna voli sama - pokud ma MZK pocit, ze hlavni skupinou uzivatelu jsou lide, kteri Krameria pouzivaji pro "seriózní vědecké práce s digitalizovanými dokumenty", tak tam muze vybrat neco serioznejsiho nez pohadky a basne.

Ne vsechny knihovny maji vedecky obsah. Nektere knihovny se zameruji na regionalni periodika - autorsky nechranena i z letoska treba.

Ne kazdy Kramerius patri (vedecke) knihovne. 
Napr. Lesnicky myslivecky digitalni archiv ma Krameria - tam urcite nejdu kvuli vedecke praci.

Obsah NDK se za "seriozni" taky moc pokladat neda. Napr. 4 po sobe jdouci nove dokumenty. 
100 + 1 navodu jak prezit manzelstvi
Caligua
Obrazky z rise hmyzu
Centralni poruchy hybnosti v praxi

Takze abych to shrnul, Kramerius je Digitalni knihovna, ne primarne nastroj pro "seriozni" vedecke prace.

A btw. vzdyt tady http://kramerius.mzk.cz/search/ mate taky seznam vybranych (jen naledy, takze z toho nejde moc poznat) a to nikomu za ty roky nevadilo??

**Comment by LenkaDamborska** [comment]
Myslím, že tady nešlo o obsah digitální knihovny, ale spíš o možnost mít nějaké profesionálnější nástroje pro vyhledávání/procházení (tím je myšlena ta seriózní vědecká práce). Psala to paní, která pracuje se znalostními databázemi. Obsah i nástroje tam vypadají dost jinak. Jasně, že digitální knihovna má jiný charakter, ale knihovníci mají na vyhledávací možnosti zkrátka větší požadavky... Pro uživatele se to ještě změní, až budou filtry atp. To pak zhodnotíme, jak dobré nástroje to pro ně budou.
