### ISSUE TITLE
Prohlížečka - šipky pro navigaci 

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#134]
"Šipky pro navigaci na další/předchozí stránku (v kulatých terčících) u zobrazených naskenovaných stránek – nechat je více viditelné, aby se při kurzoru mimo ně téměř neschovávaly – opět pro hůře vidící."

**Comment by honza-rychtar** [comment]
Muzu snizit pruhlednost.
Ale nemelo by to byt moc, aby to pak naopak neotravovalo bezne uzivatele.

**Comment by LenkaDamborska** [comment]
No,  můžeme to zkusit s tou sníženou průhledností, co?

**Comment by honza-rychtar** [comment]
Ok
