### ISSUE TITLE
Fullscreen 2

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#135]
"Když si uživatel zvolí možnost zobrazení dokumentu na celou obrazovku, jestli by se zároveň nemohla odsunout i horní „hledací“ lišta – mohla by se tak zvětšit velikost zobrazené stránky (její výška). To by uvítali zvláště ti, kteří mají širokoúhlý monitor."

-> Toť otázka... Je fakt, že velikost strany se moc nezmění, jen zmizí sloupce po stranách.

**Comment by honza-rychtar** [comment]
Viz #127
