### ISSUE TITLE
Posouvání v okně s textem

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#138]
U tohoto dokumentu (stránky) se nezobrazí při výběru TXT celý text a nedá se ani posouvat:
http://janrychtar.cz/kramerius/#/mzk/view/uuid:b82784d7-435d-11dd-b505-00145e5790ea?page=uuid:56781fdc-435f-11dd-b505-00145e5790ea
Možná by stálo za to tam přidat scrollbar.

**Comment by honza-rychtar** [comment]
Opravim. Deje se to vsude, kde je text dlouhy a nevleze se do dialogu.
