### ISSUE TITLE
Dvoustrankove zobrazeni u periodik.

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#157]
Bylo by dobre dat do metadat k dokumentu doporuceni pro dvoustrankove zobrazeni.
U periodik (viz screenshot 1) je to nekdy spis na skodu, obrovske ctyrsloupcove Lidove noviny se stejne musi hodne zazoomovat, aby byl text citelny a u dvoustrankoveho zobrazeni prechod na dalsi stranku znamena bud zpetne odzoomovani nebo pracne pozouvani - tady by bylo vhodne mit jednostrankove zobrazeni.
Naopak u periodik mensich rozmeru, napr. Ceskotrebovsky zpravodaj (viz screenshot 2) je dvoustrankove zobrazeni vhodne.
@black23 Vase periodikum se ve dvoustrankovem zobrazeni takto da pohodlne cist bez nutnosti zoomovani nebo posouvani (coz je ok u map, ale u textu to otravuje) a zaroven je prostor obrazovky vyuzity na maximum. Takze uzivatel pak jen cte a otaci stranky (po dvou strankach). 

Podobne treba u atlasu. Pro vysoke atlasy se dvoustrankove zobrazeni hodi, u sirokych atlasu ne.

Takze by bylo super, kdyby v datech bylo pro kazdy dokument doporuceni pro klienty, jestli maji nebo nemaji pouzit dvoustrankove zobrazeni - podobne to funguje u IIIF Presentation API.

1) Lidove noviny
<img width="1680" alt="screenshot 2016-02-05 17 18 11" src="https://cloud.githubusercontent.com/assets/1178142/12852058/72f129be-cc2d-11e5-8743-a816f57287c9.png">

2) Ceskotrebovsky zpravodaj
<img width="1680" alt="screenshot 2016-02-05 17 17 24" src="https://cloud.githubusercontent.com/assets/1178142/12852183/fd239c98-cc2d-11e5-849e-402885187389.png">

**Comment by honza-rychtar** [comment]
uz je mozne se na to podivat zive:
Screenshoty vyse:
1) http://janrychtar.cz/kramerius/v0.1.6/#/mzk/view/uuid:265be040-61e6-11dc-842b-000d606f5dc6?page=uuid:25e46650-61e6-11dc-8cda-000d606f5dc6
2) http://janrychtar.cz/kramerius/v0.1.6/#/mkct/view/uuid:668cd81c-6e9b-436c-9bb7-bce424c916a3?page=uuid:20c366f4-c43c-4a1e-adf4-34e3d2597d25

**Comment by black23** [comment]
Dvojstránky jsou užitečný nástroj. Jen na některých stranách se nám zobrazuje divně asi 1 cm dole na straně: 
http://janrychtar.cz/kramerius/v0.1.6/#/mkct/view/uuid:eea0f70a-35c1-494b-ba84-5696de658343?page=uuid:b5375ae2-f9ad-4d0f-a6c5-c5a6ccc09692
http://janrychtar.cz/kramerius/v0.1.6/#/mkct/view/uuid:eea0f70a-35c1-494b-ba84-5696de658343?page=uuid:bd5de273-6259-4dfc-a6ea-be4172016280

V Krameriu to vypadá lépe, i když zjevně je to špatně oříznuté.

**Comment by honza-rychtar** [comment]
Zatim vyreseno tak, ze se dvoustranky z ruznou vyskou stran neprepocitavaji (tim vznika to, ze to uplne nesedi na vysku k sobe a pri ruzne vysce skenu bude jedna stranka vyssi). 
Zoomify v OpenLayers vyzaduje presne rozmery obrazku a pri jejich zmene dochazi k artefaktum, zaroven nelze zazoomovat jen jednu stranu zvlast (jde, ale pak by to dal nefungovalo jako celek). 
Bez vetsiho zasahu do OpenLayers to zatim jinak nevyresim. Nicmene, stranky i tak k sobe pekne sedi, pokud neni chyba v orezu.
