### ISSUE TITLE
Clanky a vnitrni casti

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#163]
Do panelu s nahledy pridat taby - 3 pohledy
1) stranky - vzdy
2) clanky - pokud dokument obsahuje alespon jeden clanek
3) vnitrni casti - pokud dokument obsahuje alespon jednu vnitrni cast.

Vnitrni cast pro jednoduchst oznacovat jako 'kapitola'

V pripade pohleu 1) se bude panel chovat jako ted.
V pripade pohledu 2), resp. 3) se zobrazi seznam s nazvy clanku, resp. kapitol, ktere budou klikatelne a po vybrani se stranky vyfiltruji jen na danou podmnozinu, prejde se zpet do pohledu 1) s nahledy, kde bude nahore viditelne uvedeny nazev vybraneho clanku nebo kapitoly a moznosti tento vyber zrusit.

**Comment by LenkaDamborska** [comment]
Články tam teda jsou? Dívala jsem se na Lidové noviny a články nevidím. 
Jinak co když jsou u článků uvedení autoři? Třeba Karel Čapek publikoval v Lidových novinách, ale v klientovi se k nim přes autora nedostanu.

**Comment by honza-rychtar** [comment]
Clanky tam jsou. Kdyz koukam do lidovek tak clanky vidim jen v prvnm rocniku - v klientovi http://www.digitalniknihovna.cz/mzk/view/uuid:b82784d7-435d-11dd-b505-00145e5790ea?page=uuid:56775c82-435f-11dd-b505-00145e5790ea - v levem panelu, tab clanky.

Nebylo tam tech clanku vic? Jakoze ve vice rocnicich, nezmizely vam nejak? V K4 jsem po proklikavani taky jinde nez v prvnim rocniku clanky nenasel.

K autorum v clancich zalozim separatni issue.

**Comment by zabak** [comment]
Článků by v Lidovkách mělo být cca 53000 celkem. Není to ale rozprostřeno rovnoměrně do všech ročníků.

**Comment by honza-rychtar** [comment]
Je jich 52453 a opravdu nejsou rovnomerne rozprostrene - http://kramerius.mzk.cz/search/api/v5.0/search?q=fedora.model:article%20AND%20root_pid:%22uuid:bdc405b0-e5f9-11dc-bfb2-000d606f5dc6%22&facet=true&facet.field=rok&facet.limit=100&rows=0&facet.mincount=1

Z 53 rocniku Lidovek pripada temer polovina clanku na roky 1939 - 1942.
Takze to vysvetluje, ze pri nahodnem prochazeni Lidovek jsem na clanky nenarazil. 
Kdyz pak z toho dotazu vyse vim kde hledat, tak uz je to v pohode, napr v roce 1939 je pres 8 tisic clanku - tam je spousta clanku v kazdem cisle.

Kazdopadne klient clanky zobrazuje spravne - vylepsit jejich vyber, ruseni, prochazeni je pak druha vec, na tom jeste zapracuju.

**Comment by honza-rychtar** [comment]
Autori v clancich viz #195
