### ISSUE TITLE
Datum vydani cisla periodika

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#167]
Pro badatele je datum vydani prohlizeneho cisla periodika dulzezity udaj.
Jsou dve moznosti, jak mit tento udaj v MODSu ulozeny:
1) http://kramerius.mzk.cz/search/api/v5.0/item/uuid:b82784d7-435d-11dd-b505-00145e5790ea/streams/BIBLIO_MODS
part -> detail -> date
Tohle se propaguje do API:
http://kramerius.mzk.cz/search/api/v5.0/item/uuid:b82784d7-435d-11dd-b505-00145e5790ea

2) http://kramerius.kr-olomoucky.cz/search/api/v5.0/item/uuid:69ebfd5d-66c1-48e5-b6a7-f5f2bc545b93/streams/BIBLIO_MODS
originInfo -> dateIssued
Toto se do API nepropaguje!
http://kramerius.kr-olomoucky.cz/search/api/v5.0/item/uuid:69ebfd5d-66c1-48e5-b6a7-f5f2bc545b93

**Comment by MartinRumanek** [comment]
Blokováno https://github.com/moravianlibrary/kramerius/issues/83, budu řešit

**Comment by zabak** [comment]
Honzo, na tvé straně je toto vyřešeno, nebo ne?

**Comment by honza-rychtar** [comment]
@zabak Ano

**Comment by zabak** [comment]
Skoro navrhuji zavřít, vzhledem k tomu, co psal martin k tomu odkázanému issue u nás.
