### ISSUE TITLE
Poznamky v obrazku

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#169]
V prohlizecce pridat moznost zvyraznit si obdelnikem cast obrazku a pridat k tomu textovou poznamku.
Klient by si poznamky pomatoval po dobu session. Pokud prejdu na jinou stranu a zpet, tak se oblasti znovu vykresli. Mohlo by to fungovat i kdyz uplne odejdu z dokumentu a v ramci stejne session se k nemenu vratim.

Poznamky by melo byt mozne i editovat.

Pri opetovnem otevreni klienta se poznamky ztrati. S tim na urovni klienta nic neudelam.
Ale je to pekna moznost rozsireni Krameria, ktery by si uzivatelske poznamky pomatoval a pres API by je zpristupnoval. Uzivatel by tak mel poznamky ulozene trvale a pristupne ve vsech klientech.

Hodi se to zejmena badatelum, kteri maji otevrene desitky vytisku, kde si najdou nejaky kontext a pozdeji se k nim vraci. Takze v jednom vytisku provedou treba 10 hledani, ale zvyrazneny vysledek jim zustene jen u posledniho hledani. Pokud by mohli vytvaret poznamky, tak by meli pri dalsim hledani zvyrazneny kontext z predchoziho hledani.

**Comment by zabak** [comment]
Máš na mysli něco jako Open Annotation a http://iiif.io/api/annex/openannotation/ ?

**Comment by honza-rychtar** [comment]
Ne nutne. To nemusi byt reseno nejakou existujici specifikaci. Byla by to soucast Krameria.
Staci tabulka v databazi **notes**, ktera by mela 6 sloupcu

1) **id** je id poznamky
2) **user_id** je id uzivatele
3) **uuid** je uuid stranky
4) **bb** je bounding box, staci jako string napr. "0,0 100,100 100,0 0,100" by byl ctverec v levem hornim rohu o delce strany 100px
5) **color** by byla barva poznamky - stejne jako si clovek prilepuje barevne nalepky
6) **text** by byl text poznamky

na 1) a 2) a 3) by byl index

Pres API by bylo mozne
1) ziskat seznam poznamek pro uzivatele pres **user_id** 
2) ziskat seznam poznamek pro stranku pres **uuid**
3) ziskat poznamku pres **id**
4) upravit poznamku pres **id**
5) smazat poznamku pres **id**
6) vytvorit poznamku pro **uuid** a **user_id** 

Zbytek zajisti klienti

**Comment by MartinRumanek** [comment]
Právě, že by bylo dobré, aby to v API bylo podle specifikace. Prohlížečka Mirador to umí a budou na to vznikat i další nástroje. Proč to dělat od začátku nekompatibilní?

**Comment by zabak** [comment]
Základní koncepční rozhodnutí je, jestli půjde o veřejné nebo soukromé anotace, nebo jestli je bude možné nastavit jedním nebo druhým způsobem. Nebo jestli tam mít i klasické sdílení s více uživateli.

**Comment by honza-rychtar** [comment]
@MartinRumanek Rozsireni Kramerius API o jednu vec z IIIF API?
Ono tohle http://iiif.io/api/annex/openannotation/ slouzi trosku k necemu jinemu. Definuje vyrez obrazku, ne popis casti obrazku. 
To by se dalo pouzit spis nasledne, kdy si uzivatel definuje pres poznamku nejaku oblast, napr clanek v novinach a pak si bude chtit tuhle oblast stahnou jako JPEG.
Pres Open Annotation by to asi slo, ale zase jak bude vypadat request a odpoved pro pozadavek na seznam anotaci uzivatele X a stranky Y.
Navic definice anotaci pro obrazek je uvnitr presentation API. Bez presentation API je stejne potrebuju nejak namapovat na konkretni stranku a konkretniho uzivatele.

Hlavne je uplne jedno jak to API bude vypadat - jen by melo obsahovat tech 6 volani, ktere jsem uvadel v predchozim komentari. 

@zabak Uzivatelske poznamky urcite soukrome. Verejne anotace by davaly smysl napr. u vyrezu clanku v novinach, kde by se seznam clanku dal delat pres toto a zaroven pri otevreni clanku by se nacetl opravdu jen vyrez novin. 
Dalo by se udelat neco jako u Georeferenceru, ze nechas uzivatele oznacovat a popisovat oblasti s clanky v periodikach :)

**Comment by honza-rychtar** [comment]
Issue zavira,. Klientska cast je hotova a serverovou cast nema smysl resit tady.
S @MartinRumanek resime, ze by se daly poznamky ukladat do profilu uzivatele - to by fungovalo s aktualni funkcionalitou Krameria.
