### ISSUE TITLE
Pouze veřejné - není jasné která poloha přepínače je zapnuto a která vypnuto

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#17]
Možná by se mohl ten nápis měnit "Zobrazeny pouze veřejné dokumenty" "Zobrazeny všechny dokumenty"

**Comment by honza-rychtar** [comment]
Je to Material Design komponenta - Switch - ktera ma jasne specifikovany vzhled a vyznam poloh.
http://www.google.com/design/spec/components/switches.html#switches-switch

Mozna by sel menit ten popis - vsechny dokumenty/pouze verejne - pak by ale zase nebylo zrejme co ten prepinac dela, musel bych ho zkusit prepnout tam a zpet, abych videl jeho vyznam.
Pokud tam necham jen "pouze verejne" a prepinac beru jako true/false, tak je to podle me nejprirozenejsi.

Je to spis o tom, jak jsou lidi zvykli na tuto komponentu.

**Comment by pavluska** [comment]
Akorat bych ten prepinac dala hned pod vyhledavaci okynko, takhle je moc
dole a nekdo by ho mohl snadno prehlednout...

čt 19. 3. 2015 v 13:58 odesílatel Jan Rychtář <notifications@github.com>
napsal:

**Comment by zabak** [comment]
Petra když jsem jí ho ukázal tak nepoznala že jde o přepínač. Když se to dozvěděla, tak poznala která poloha je zapnutá (já nad tím musím pokaždé přemýšlet, protože beru že když je bílý tak je rozsvícený, to je přece jasné). Zkuste udělat víc uživatelských testů (Bára, Veronika,...) co řeknou. Taky by ten popis měl být explicitnější (Prohledávány všechny dokumenty/ prohledávány jen veřejné dokumenty.

**Comment by honza-rychtar** [comment]
Prepinatko se zrusi
Viz #137
