### ISSUE TITLE
Fasety u fulltextoveho hledani.

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#177]
Fasety obsahuji pocty dokumentu pro kazdou polozku jen pro nalezy v metadatech. Fulltext se nezapocitava (krome dostupnosti).
Takze pokud hledam napr. "Karel Čapek", tak u typu dokumentu se zobrazi:
Knihy 332
Zvukove nahravky 1
Toto jsou nalezy v metadatech. V periodikach se hledany vyraz v metadatech nenasel, pocet je nula a polozka se tak skryje. 
Ve fulltextu se ale vyraz v periodikach nasel, ale protoze je polozka skryta, tak nemuzu vysledky hledani omezit jen na periodika.

**Comment by zabak** [comment]
K5 klient vrací na stejný dotaz Monografie (7749)
Periodikum (532)
Kolekce nahrávek (1)

K4 zobrazuje jen typy dokumentů bez počtů.

**Comment by honza-rychtar** [comment]
Ted se u fulltextu zobrazuji vzdy vechny typy dokumentu (ktere existuji ve vybrane knihovne).
Zaroven se zobrazuje u typu dokumentu pocet nalezu ve fulltextu. 

Pocty s K5 klientem stale nesedi, protoze K5 klient zobrazuje mix nalezu v metadatech, nalezu ve fulltextu s presne zadanym textem a pocet nalezu ve fulltextu s libovolnym poradim slov.

Prijde mi lepsi jasne oddeli nalezy v metadatech a nalezy ve fulltextu - v poctech i primo na kartach.

Vysledky fulltextu s libovolnym poradim slov ignoruju, protoze je to imho zbytecne - najde to neco, co vubec nechci. O tomhle muzeme dal diskutovat, je mozne, ze i tyto vysledky budou zadane.

Taky upozornuju, ze vyber jazyka, klicovych slov nebo autora fulltextove hledani zrusi - tyto informace nejsou na urovni stranek, kde se se fulltextove hledani provadi, takze pokud vyberu ve fasetech napr. autora, tak jsou fulltextove vysledky prazdne, protoze zadna stranka vybraneho autora neobsahuje.
Fulltextove vysledky se pouziji jen pokud 
1) je zadany hledany retezec
2) ve fasetech je omezeni jen na dostupnost, typ dokumentu, nebo rok.
