### ISSUE TITLE
našeptávač a mouseover

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#178]
Pokud začnu psát vyhledávací dotaz a přejedu myší nad našeptanými knihami, tak se zvýrazňují. Když ale odjedu myší mimo nabízené dokumenty, tak zůstane jeden z nich zvýrazněný. Když dám Enter, tak se nevyhledá to co jsem napsal ale naposledy zvýrazněn, což je špatně, protože jsem na žádný nekliknul.

**Comment by honza-rychtar** [comment]
Opraveno. Pokud odjedu kurzorem ze seznamu, tak se polozka odznaci a entrem se pouzije vypsany text.
