### ISSUE TITLE
české znaky v kontextu fulltextového vyhledávání

### ISSUE THREAD

**Issue by rzeh4n** [honza-rychtar/kramerius-web-client#18]
Někdy se špatně zobrazují české znaky v textu obalujícím vyhledávaný řetězec ve fulltextovém vyhledávání.
Např:
http://janrychtar.cz/kramerius/#/periodical/uuid:73f3e41a-65c9-11e0-b4ae-0050569d679d?fulltext=Brno
Asi je to v datech, tady to je zase v pořádku:
http://janrychtar.cz/kramerius/#/periodical/uuid:ae7b52cd-435d-11dd-b505-00145e5790ea?fulltext=Brno

**Comment by zabak** [comment]
@rzeh4n: Není toto už vyřešené? Z těch příkladů není jasné co je za problém

**Comment by honza-rychtar** [comment]
Vyresene to neni, ale klient s tim nic nenadela. U nekterych dokumentu je pouzite spatne kodovani OCR

**Comment by zabak** [comment]
Už to vidím. Toto je tedy bug na naší straně a toto issue si prosím zavři.
