### ISSUE TITLE
skrolování ve fasetách

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#181]
Misto skrolování jednotlivých faset dát možnost rozkliknout "více" nebo otevřít okno nebo sloupec kde se vejde těch faset opravdu hodně - např jako u http://techlib.summon.serialssolutions.com/

**Comment by honza-rychtar** [comment]
Zmenim to na "zobrazit vice", "zobrazit mene". Taky me to scrollovani uvnitr scrollovatelneho panelu uz stve.
