### ISSUE TITLE
Nefunguje vybírání textu: Ke stránce není vygenerovaný textový přepis.

### ISSUE THREAD

**Issue by black23** [honza-rychtar/kramerius-web-client#182]
Funguje je to jen s ALTO nwbo i s klasickým OCR? Protože s OCR se mi to nezdařilo zatím nikdy vybrat.

**Comment by honza-rychtar** [comment]
Bez ALTA nezjistim cast textu ve vybrane oblasti.
Ale je fakt, ze zobrazeni hlasky "Ke stránce není vygenerovaný textový přepis" je spatne. Textovy prepis vygenerovany je, jen neni ALTO. Mohla by se nabodnout moznost zobrazit OCR cele stranky treba.

**Comment by black23** [comment]
Jasně, myslel jsem si to. Problém je v tom, že ALTO má jen zlomek dokumentů. Takže bych opravil alespon tu hlášku naznačeným způsobem. Nebo zjistit přítomnost ALTO a možnost vybrat text nabídnout až poté.

**Comment by zabak** [comment]
Navrhuji toto issue zavřít, v #262 je i návrh jak to řešit.
