### ISSUE TITLE
Pridat do metadat informaci o knihovne, ze ktere se otevreny dokument bere

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#190]
Do metadat v pridat:
Zdroj
Knihovna X

Knihovna X bude knihovna, ktera je v aplikaci vybrana (pri odkazovani rovnou do prohlizecky nemusi byt zrejme a taky se nemusi shodovat s mistem ulozeni). Klikem na nazev knihovny se otevre novy tab s dokumentem v K4 klientovi vybrane knihovny.

Pridat tuto funkci do konfigurace. Pokud mam nasazeneho klienta jen pro jednu knihovnu, tak je to zbytecne.

**Comment by LenkaDamborska** [comment]
Toto souvisí se zobrazením loga knihovny v prohlížečce vpravo dole?

**Comment by honza-rychtar** [comment]
Ano

**Comment by honza-rychtar** [comment]
Bude se to tykat jen www.digitalniknihovna.cz
U vlastnich instalaci je zdrojova knihovna jasna a je vetsinou zobrazena primo v nazvu aplikace vlevo nahore v toolbaru.

**Comment by honza-rychtar** [comment]
V podrobnostech je ted ZDROJ, kde je logo a nazev zdrojove instituce a nazev je klikatelny. Proklikem se otevre novy tab s webem instituce.
