### ISSUE TITLE
návrat na výsledky vyhledávání přeskočí na první vyhledávání

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#197]
Z hlavní stránky zadám vyhledávací dotaz. Pak další, nebo několik. Pak kliknu na nějakou knížku (aby se zobrazily náhledy stránek), pak kliknu na "<- digitální knihovna" a jsem zpět na výsledcích toho prvního vyhledávání.

**Comment by honza-rychtar** [comment]
Opraveno, bude ve verzi 0.2.8
