### ISSUE TITLE
odstranění vyhledávacího dotazu nezobrazí všechny stránky dokumentu

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#198]
Příklad: http://www.digitalniknihovna.cz/mzk/search/?q=onkochirurgie - kliknu si na "Onkochirurgie II. Orgánová chirurgie I" (má hity ve fulltextu). Zobrazí se mi náhledy stránek 1,2,3,4,51,87. Kliknu vlevo na křížek u vyhledávacího dotazu (vymažu dotaz). Zobrazí se mi náhledy stran 1a,1b,1,2,3,4,5,6,7,8.

**Comment by honza-rychtar** [comment]
To jsem tam zanesl v minule verzi.
Uz je opraveno. 
Bude ve verzi 0.2.8
