### ISSUE TITLE
V metadatech dokumentu se nezobrazuje podnázev, který je vidět v seznamu vyhledaných dokumentů

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#199]
viz. např. prvních několik knih z http://www.digitalniknihovna.cz/mzk/search/?q=onkochirurgie - v seznamu je ještě podnázev, který ale po rozkliknutí knihy není v metadatech vlevo vidět.

**Comment by honza-rychtar** [comment]
Tohle jsou pripady, kdy se nepouziva title a subtitle, ale title a partName.
Vysledky vyhledavani se berou ze SOLRu, ktery bere data z DC - tam se seskupuje nazev do jednoho pole takto:
a) Pokud je pouzity subtitle, spoji se pres dvojtecku - title : subtitle
b) Pokud je pouzity partName, spoji se pres tecku - title. partName

V metadatech pak beru metadata z MODS, kde jsou nazvove casti zvlast.
title zobrazim vyrazne nahore a pod nim zobrazim mene vyrazne subtitle (pokud existuje).
S partName jsem nepocital. Pridam ho do metadat - zobrazim ho stejne jako subtite.

Co delat v pripade, kdy je pritomny subtitle i partName - co je dulezitejsi, mam zobrazovat oba a v jakem poradi?
Zobrazeni metadat by melo zustat prehledne, tj. jen uvest vyrazne nazev a pod nim jemneji doplnujici nazev - ne zpusobem klic:hodnota pro kazdou nazvovou cast: nazev:A, podnazev:B, nazev casti: C, cislo casti: D ....

Nevite o nejakych dokumentech, ktere maji subtitle i partName?

**Comment by pavluska** [comment]
Logicky by mel byto byt poradi nazev, podnazev, cislo casti, nazev casti. Podnazev je soucast nazvu celku, cislo a nazev casti patri, jak jiz nazev napovida, k casti :) 

Jako priklad jsem nasla napr. [totok](https://vufind.mzk.cz/Record/MZK01-000712392/Details#tabnav)... tady je zajimave, ze se to zdigitalizovalo 2x, jednou pravdepodobne jeste v K3, protoze metadata jsou spojena do jednoho, z ndk to mas pekne rozepsane :) V [tomto](http://www.digitalniknihovna.cz/mzk/view/uuid:803b2cac-d74d-11e0-94b2-0050569d679d?page=uuid:803cda5d-d74d-11e0-94b2-0050569d679d) je spojeny nazev, cislo a nazev casti do jednoho, v [tomto](http://www.digitalniknihovna.cz/mzk/view/uuid:39cd1a70-7443-11e2-86a5-005056827e52?page=uuid:86ea8f93c7866b146080cec604486385) to mas zvlast vcetne alternativniho nazvu. 

Dokumenty tohoto typu budou zkatalogizovane ruzne. Treba slovniky tak, ze bude jen nazev celku a nazvy casti budou v jednotkach, takze do modsu se nepropisou. Nevim, jestli se to v ndk zapisovalo rucne nebo ne. Ale to asi zatim neres.

Vufind to zobrazuje v jednom radku vsecko. Já bych treba byla spis pro to, at je nazev vyrazne, podnazev mene vyrazne a pod tim jeste trochu mene vyrazne cislo a nazev casti. Bez tech "klicu".

**Comment by luckajirku** [comment]
Další, co s tím souvisí, je edice (v MARC21 pole 490, v modsu relatedItem/titleInfo/title). Ta se zcestně zobrazuje místo hlavního názvu. 
Viz např. http://www.digitalniknihovna.cz/svkhk/view/uuid:5a8a8b5e-5115-4ffa-b258-301b94d8c31c
- místo názvu České pohádky Karla Jaromíra Erbena je tady Klub mladých čtenářů (Albatros).
Zobrazení v K4 http://kramerius4.svkhk.cz/search/handle/uuid:5a8a8b5e-5115-4ffa-b258-301b94d8c31c a odkaz do OPACu: https://aleph.svkhk.cz/F?func=direct&doc_number=000103717&local_base=katalog&format=999.

**Comment by honza-rychtar** [comment]
Opravim, bere se prvni vyskyt titleInfo/tite, vy mate v MODS hlavni nazev az za relatedItem, takze jako prvni narazi na nazev v relatedItem. Zmenim to, aby se bral nazev z mods/titleInfo/title.

Jsou nazvy z relatedItem pro uzivatele zajimave? Pokud ano, jak je zobrazit, aby ruzne typy nazvu nezabraly pul obrazovky?

**Comment by honza-rychtar** [comment]
Hlavni nazev opraven uz drive.
Nazvove informce se ted zobrazuji takto:

title
subtitle
partNumber: partName
