### ISSUE TITLE
Pri vyberu polozev v hlavnim menu probliknou ikony polozky

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#202]
Zvyraznene ikony se nactou az po aktivaci polozky, pri vyberu tak dochazi k neprijemnemu probliknuti.

**Comment by zabak** [comment]
Buď jsem to nepochopil, nebo je to už vyřešené a dá se zavřít.

**Comment by honza-rychtar** [comment]
Uz bylo vyresene, zaviram.
