### ISSUE TITLE
zobrazení rights message

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#206]
v případě MZK má informace 3 odstavce a každý má vlastní scrollbar. Navíc je součástí obrázek, ten se nezobrazí vůbec

**Comment by honza-rychtar** [comment]
Pokud jde o obrazek, tak na ten v right message linkujete relativne "samolepka.jpg" - tohle nebude fungovat jinde nez v K4 klientovi (obrazek je tady http://kramerius.mzk.cz/search/samolepka.jpg)
Na text se da podivat v registru - http://registr.digitalniknihovna.cz/libraries/1 (obrazek taky chybi).
V right message zmente img src na absolutni url a taky mozna presunte ten obrazek na stabilnejsi misto, kde nedojde k jeho nechtenemu smazani napr. updatem Krameria (nebo migraci do OpenShiftu), treba http://www.mkz.cz/assets/images/samolepka.jpg

Pokud jde o klienta, tak ten v tuhle chvili ani nebere right message pres API - ta hlaska je tam pevne pro vsechny knihovny (coz je diky odkazum na MZK spatne).
Zmenim to na obecnou hlasku pro vsechny knihovny. 
Vlastni text konkretni knihovny bude az dovysvetleni - 
right message neni ve vsech verzich API (http://registr.digitalniknihovna.cz/libraries/8)

, ktere jsou v klientovi, ale hlavne nektere knihovny tam maji defaultni

**Comment by honza-rychtar** [comment]
Zmenil jsem to na obecny text, ktery se nevztahuje k zadne knihovne.
*Tento dokument si nemůžete volně prohlížet kvůli autorským právům. Autorský zákon připouští zpřístupnění děl 70 let po smrti všech autorů (včetně překladatele, ilustrátora atd.) a 50 let od vydání díla.*
Text je lokalizovany do slovenstiny, anglictiny a nemciny.

Vlastni text **rightMsg** zatim na www.digitalniknihovna.cz pouzivat nebudu. 
Vetsina knihoven ma jen vychozi text "Tento dokument není veřejně přístupný.", nektere dokonce jen v anglictine. Par knihoven ma viceme to same jako vyse zmineny obecny text.
MZK linkuje relativne na obrazek, ktery se timto nenacte a jen rozbije vzhled.
Taky kazdy pouziva jine formatovani pro nadpisy - nekdo **h1**, nekdo **h3**, nekdo jen **b**
 
Pro vlastni instalaci klienta necham v konfiguraci moznost pouziti vlastniho textu v Krameriovi.
