### ISSUE TITLE
Zobrazení vícesvazků

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#207]
Vícesvazky jsou další kapitola... Vytváří se tak, že se napojí volná část (physical unit) na titul a v ní jsou ty jednotlivé svazky (volume). Třeba tady je příklad klasického vícesvazku: http://kramerius.mzk.cz/search/handle/uuid:be9390c0-4bd4-11e5-8b04-5ef3fc9bb22f 
V klientovi to vypadá takto: http://www.digitalniknihovna.cz/mzk/view/uuid:be9390c0-4bd4-11e5-8b04-5ef3fc9bb22f?page=uuid:a23143e0-4cd9-11e5-8851-005056827e51
Obrázky obou svazků teď jdou za sebou a metadata se zobrazují pouze ta k hlavnímu titulu. Ty stěžejní údaje jsou v metadatech u volume, v klientovi zatím nejsou. 

Může se to řešit jako u periodik, že se půjde přes jednu úroveň navíc, než se člověk dostane ke svazkům, nebo ještě jinak. Bude potřeba to společně promyslet.. Přímo při prohlížení by se mohlo plynule přecházet k druhému svazku jako je to u ročníků a čísel (předchozí, následující).

**Comment by honza-rychtar** [comment]
Tohle je model monographunit, kdy je monograph rozdelena na vice monographunit a az ty obsahuji stranky.
Kdyz jsem podporu pro monograph unit pridaval, tak jsem prave premyslet jestli to udelat jako dalsi uroven (jako u periodik). To mi prislo uzivatelsky nepohodlne, tak jsem to udelal jako je to ted - prohlizecka si z monografie nacte vsechny stranky a taky se podiva, jestli nema nejake monograph unit, pokud ma, tak se pro kazdou monographunit nactou stranky a zaradi nakonec seznamu.

Prislo mi to jako nejjednodussi reseni (uzivatelsky, z pohledu implementace je nejjednodussi tam vrznout dalsi uroven) - i kdyz tim vlastne odbouravam pouziti teto struktury.
Metadat jsem si ale nevsimnul. Mas pravdu, ze na urovni monografie tam nic moc neni a vse je az na urovni monographunit.
V tom tvem pripade jesou dve monographunit a maji stejna metadata krome partNumber a partName:
1) http://kramerius.mzk.cz/search/api/v5.0/item/uuid:7ec15740-46f5-11e5-8851-005056827e51/streams/BIBLIO_MODS
2) http://kramerius.mzk.cz/search/api/v5.0/item/uuid:91e41280-b9c4-11e5-b5dc-005056827e51/streams/BIBLIO_MODS

Ted je otazka jestli ma pro uzivatele vubec nejaky vyznam tuhle strukturu pouzivat a neni pro nej jednodussi, kdyz ma vsechny monographunit slouceny do jedne.
Ten ukazkovy priklad, ale i priklady, na kterych jsem kdysi testoval monographunit, maji celkove jen desitky az stovky stranek a rozsekavat to na casti nemusi byt pro uzivatele prinosne, spis ho to bude otravovat (at uz dalsi urovni, nez se vubec dostane do prohlizecky, nebo preklikavanim v metadatech).
Opakuju "pro uzivatele", z pohledu katalogizace tu strukturu chapu, ale ne vse se musi odrazit v prezentaci.

Mohla by tam byt moznost zobrazit si jen konkretni monographunit (jako v pripade clanku a kapitol), ale jako vychozi zobrazeni by se vzaly vsechny stranky. Takzy by tam moznost zobrazit si to v originalni strukture byla.

**Comment by zabak** [comment]
Je pak ale matoucí, že ty stránky na sebe tak natvrdo navazují. Když hledáš třeba 3. díl něčeho, tak si nemusíš všimnout předělů mezi svazky apod. Navíc ty vícesvazky můžou být větší, třeba ottův slovník naučný apod.

**Comment by honza-rychtar** [comment]
Ok, uznavam, ottuv slovnik naucny takto delat nepujde - po otevreni to nacita stranky pro vsech 28 casti, kde uz kazda cast je hodne velka, dlouho to trva a nakonec mam v prohlizecce 30276 stranek :)
http://www.digitalniknihovna.cz/mzk/view/uuid:7e11fe20-043e-11e5-95ff-5ef3fc9bb22f

Takze to asi udelame jako u periodik co?
Ze se nacte seznam svazku a po prokliku se zobrazi prohlizeccka jen pro tento jeden vybrany.
Metadata by se pak nacetla pro vybrany svazek a dalo by se z metadat prechazet na predchozi a nasledujici svazek a zpet na seznam svazku (jako v pripade cisla periodika).

**Comment by LenkaDamborska** [comment]
Jo, monographunit jsem chtěla napsat :) Popsala jsem to podle toho, jak se to jmenuje na webu. 
Nemyslela jsem, že je to vyloženě špatně, jak to máš teď. Ono záleží na tom, jak k tomu člověk přistupuje. Když si chce přečíst celou knihu, přejde plynule z jednoho svazku do druhého a nemusí řešit nějakou další úroveň. Ale zase když jde po určitém svazku, tak ten seznam potřebuje, aby díl nemusel hledat v levém sloupci mezi obrázkama. 

Ještě mě napadlo a vlastně to je i to, co jsi navrhoval, že by tam byla v levém sloupci viditelná možnost zobrazit si jen konkrétní svazek, jako u těch článků. Třeba by byly "stránky" a vedle toho "díly". Ale zas nevím, co by se dělo s metadaty, jestli by se zobrazovaly všechny rovnou anebo až při výběru dílu.

**Comment by honza-rychtar** [comment]
Udelame to jako periodika, priklady pouziti monographunit jako je ottuv slovnik naucny nam ani jinou moznost nedavaji. On ma celkem 30 tisic stran, tam ta struktura smysl dava a ani by to bez ni rozumne udelat neslo.

Takze pokud jde o pruchod a zobrazeni vicesvazkovych monografii:
Po rozkliknuti monografie, ktera obsahuje monographunit (dale svazky) se neprejde do prohlizecky, ale do podobne obrazovky jako v pripade rocniku periodika. Zobrazi se vpravo metadata k cele monografii a vlevo seznam svazku.
Po vybrani svazku se prejde do prohlizecky, kde budou stranky pouze z tohoto svazku.
Metadata se zobrazi pro dany svazek a ne pro celou monografi (na rozdil od cisla periodika, kde se berou metadata z celeho periodika). 
V metadatech (tak jako v pripade cisla periodika a jak jsi navrhovala) by se dalo prechazet na predchozi a nasledujici svazek a taky na seznam vsech svazku.

Dalsi veci je vyhledavani.
1) Vyhledavani v metadatech:
Tady bych zachoval hledani jen na urovni korenovych modelu, takze by se v metadatech svazku nevyhledavalo - ten ukazkovy priklad (Fyzika pro zakladni skolu) ma na urovni monografie omezena metadata - http://kramerius.mzk.cz/search/api/v5.0/item/uuid:be9390c0-4bd4-11e5-8b04-5ef3fc9bb22f/streams/BIBLIO_MODS
Napr. u nakladatelskych udaju je jen nazev nakladatele, klicova slova a autor chybi uplne.
Na urovni svazku - http://kramerius.mzk.cz/search/api/v5.0/item/uuid:f47d9693-e7a1-45cc-9f0d-c858ab706951/streams/BIBLIO_MODS 
Je u nakladatelskych udaju i misto a rok, jsou tam autori, klicova slova, .... tohle vse by melo byt i na urovni cele monografie.
Jedine co dava smysl, aby bylo v metadatech pouze na urovni svazku je nazev a cislo casti, signatura, obsah a poznamy ke konkretnimu svazku.
Pavla rikala, ze je to spatne zpracovane. Takze to beru za chybu a napr. pres autora toto nepujde najit, protoze chybi na urovni monografie, kde by byt mel.
Navic v pripade ottova slovniku by zapocitani svazku vedlo k tomu, ze po hledani "ottuv slovnik" v metadatech by ve vysledcich hledani bylo 29 vysledku pro jednu vec (1 monografi a 28 svazku).

2) Fulltextove hledani
Tady uz se musi vicesvazky zapocitat.
Pokud bych nasel hledany retezec na 150. strance 10. svazku v monogrfii X, tak nemuzu v pripade viceurovnoveho prochazeni vicesvazkovych monografii zobrazit ve vysledich hledani jen monografie X (1 vyskyt), protoze po rozkliku nejdu do prohlizecky, ale do seznamu svazku.
Tazke jsou dve moznosti:
A) Zobrazim jen celou monografi, kde po rozkliku se fulltext prenese do seznamu svazku a zobrazi se jen ty svazky, v kterych se retezec ve fulltextu nasel, ten by se pak prenesl i po otevreni svazku.
B) Svazky se u fulltextoveho hledani budou brat jako korenove modely a budou ve vysledcich primo.
Tady je problem, ze na urovni monografie nevim, ze obsahuje svazky a nemuzu ji z vysledku odfiltrovat.

**Comment by LenkaDamborska** [comment]
Honzo, k tomu bodu 1) tě asi moc nepotěším, ale obávám, že se tak vícesvazky metadatově zpracovávají. Třeba tento vícesvazek na úrovni monografie taky skoro nic nemá: http://kramerius.mzk.cz/search/handle/uuid:3eac2ef0-f52a-11e3-add3-001018b5eb5c
Podle národního standardu jsou na úrovni monografie v případě vícesvazku povinná pouze pole title, subTitle, publisher, edition, genre a identifier. Ostatní metadata jsou v těch monographunit :(

**Comment by pavluska** [comment]
Ahoj,

ale to, ze nektera pole nejsou povinna, neznamena, ze tam nejsou vyplnena.
Zalezi, jak to v ndk delate. Podle toho prikladu, cos posilala, to vypada,
ze metadata z Alephu se stahnou k urovni dilu monografie a jenom par veci
je propagovanych smerem nahoru. Ve starych datech to bude jinak. V datech z
jinych knihoven to taky bude jinak :)

S vicesvazky bude vecny problem.

P.

út 29. 3. 2016 v 18:28 odesílatel LenkaDamborska <notifications@github.com>
napsal:

**Comment by LenkaDamborska** [comment]
Jo, je to pravda. Může to být v různých knihovnách jinak nebo i u starší digitalizace jinak. Každopádně NDK, která těch vícesvazků bude mít asi nejvíc, to má takto. Proč to tak je, nevím.. Jinak když je to nepovinné, tak podle mě to spíš nebude ani u dat z jiných knihoven, protože ty se řídí tímto standardem.
Člověk o tom začne přemýšlet, až když je nějaký problém při zpřístupnění.

**Comment by luckajirku** [comment]
Ta metadata budou knihovna od knihovny. My tam třeba máme i na úrovni vícesvazku v podstatě vše, co stáhneme s bib záznamem. V ProArcu v NDK formuláři to sice nevidím, tam jsou jen ta povinná pole, ale v xml už je vidět vše. V Krameriovi se to pak ukazuje v popise komplet. Třeba:
http://kramerius4.svkhk.cz/search/handle/uuid:d420a1f3-6061-470e-a18c-7520bf6cba08
a http://www.digitalniknihovna.cz/svkhk/view/uuid:d420a1f3-6061-470e-a18c-7520bf6cba08

**Comment by LenkaDamborska** [comment]
@luckajirku Tak to je dobře, že to máte tak pěkně :) Díky za příklad. 
No, v NDK workflow by bylo potřeba to změnit. Už jsem to začala řešit s Prahou, ale při tom, jak nasazení a testování změn trvá dlouho, neslibuju, že to bude hned. Spíš to bude na dlouho. Teď trvalo 2 roky, než se zapracovaly změny do linky. Na začátku NDK tento typ dokument vůbec nebyl brán v potaz a dodělávalo se to až zpětně. Byl tlak, aby výsledná změna byla co nejmenší a co nejméně nákladná. Takže se zvolil co nejmenší bibliografický popis.

**Comment by honza-rychtar** [comment]
Hotovo. Vicesvazky se prochazeji jako periodika.
