### ISSUE TITLE
Číslo části chybí

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#208]
V klientovi není číslo části u tohoto dokumentu: http://www.digitalniknihovna.cz/mzk/view/uuid:5d935cf0-b9c6-11e5-b5dc-005056827e51?page=uuid:e4c9e0a0-e6b6-11e5-8745-005056825209
Mělo by tam být číslo části 5 jako tady: http://kramerius.mzk.cz/search/handle/uuid:5d935cf0-b9c6-11e5-b5dc-005056827e51
To číslo by se mělo zobrazit i ve vyhledaných výsledcích za názvem (v DC to je): http://www.digitalniknihovna.cz/mzk/search/?q=Monitoring%2520vybran%25C3%25BDch%2520p%25C5%2599irozen%25C3%25BDch%2520spole%25C4%258Denstev Tam je problém kvůli dlouhému názvu?

**Comment by honza-rychtar** [comment]
Zatim jsem pridaval jen nazev casti, cislo casti pridam - viz #199 jak pise Pavla.
U vysledku hledani je to kvuli dlouhemu nazvu, celkove se nacte:
"Monitoring vybraných přirozených společenstev a populací rostlinných indikátorů v České republice. 5"
Jen neni prostor to zobrazit cele.
