### ISSUE TITLE
Řazení virtuálních sbírek podle abecedy

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#212]
Jak sbírek přibývá, tak by mělo smysl je nějak řadit. Viz též https://github.com/ceskaexpedice/kramerius/issues/409
Ale možná by mohlo nějaké řazení nebo strukturování být už na straně serveru?

**Comment by honza-rychtar** [comment]
V tuhle chvili by melo smysl pracovat se sbirkama jako s jinymi typy u prochazeni. Ze by to byla jen dalsi kategore u prochazeni, stejne jako napr. klicova slova: http://www.digitalniknihovna.cz/mzk/browse/?category=keywords&sort=occurrence&accessibility=all&display=grid

Sbirky jsou zatim jen dvojjazycne pojmenovanym priznakem pro skupinu dokumentu, tedy to stejne jako napr. u klicovych slov nebo jazyka.

Porad doufam (uz resime minimalne 2 roky), ze se moznosti sbirek rozsiri a bude tedy davat smysl je mit zvlast. 

Razeni smysl dava. Zatim to staci delat na klientovi - pokud je sbirek (rekneme) mene nez sto, tak si je klient muze stahnout vsechny a pak je radit sam. Pokud by jich byly stovky, pak by mel klient stahovat sbirky postupne (pres offset a limit) a nemohl tak radit vysledky sam.

Kdyz uvadite "server", "jadro Krameria", "deaktivace/ladeni v konfiguraci aplikace", tak tim doufam myslite jen a pouze API. Pri stavajici funkcionalite nema smysl do backendu zasahovat! Jen se zmeni API - tj. rozhrani mezi backendem a frontendem. 
API sbirek by se obohatilo o parametry limit, offset, sort
Takze napr. dotaz:
http://kramerius.mzk.cz/search/api/v5.0/vc?offset=5&limit=10&sort=asc
By vratil 6. az 16. sbirku, serazeny podle abecedy vzestupne.

Dalsi veci je rozsireni informaci o sbirce (zase jen na urovni API) o pocty dokumentu uvnitr sbirky.
Tahle informace v API neni, klienti ji nezobrazuji.
Ja tuhle informaci ve webovem klientovi mam: http://www.digitalniknihovna.cz/mzk/collections/
Ale musim to delat pres dotaz na API, kde ziskam sbirky (id a nazvy) a dalsi dotaz do solr, kde ziskam id a pocty - tohle potom namapuju a muzu tak zobrazit u sbirek i pocty dokumentu.
To by API mohlo (melo!!) umet samo o sobe.

V pripade razeni taky upozornuju na existenci anglickych a ceskych nazvu.
Takze v pripade razeni na strane API by se mel specifikovat i jazyk, podle nehoz chci vysledky seradit.
Pokud by klienti spolehali na serazeni na strane API, tak by museli pri zmane jazyka polozit dotaz na API znova, coz muze byt neprijemna UX.

V tuhle chvili je problem s abecednim razenim kodovych poli, napr jazyk je ulozen jako ISO 639-2 kod, klient vezme pres Solr jazyky serazeny podle abecedy - uplatni se vsak na kody, ne na koncove lokalizovane nazvy jazyku a serazeni tak neni korektni.

**Comment by honza-rychtar** [comment]
Hotovo
