### ISSUE TITLE
Model supplement u periodik

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#213]
Mám otázku, jak je to s přílohami v periodiku (model supplement a vazba z ročníku hasIntCompPart). U Brněnských novin se pod ročníky nezobrazují přílohy. K příloze jsem se dostala fulltextem, ale tam není možnost se dostat do periodika, jen do zbytku přílohy (tady ještě chybí datum vydání přílohy):
http://www.digitalniknihovna.cz/mzk/view/uuid:8daa5830-81e2-11e3-a70e-005056822549?page=uuid:831463a0-863f-11e3-a70e-005056822549

**Comment by honza-rychtar** [comment]
Podporu pro prilohy pridam.
Jak by to melo fungovat? 
Kdyz se podivam na potomky jednoho z rocniku Brnenskych novin (http://kramerius.mzk.cz/search/api/v5.0/item/uuid:c3a174b0-31a5-11e3-a5bb-005056827e52/children), tak tam vidim 23 cisel a 23 priloh - je to na stejne urovni a v poradi 1.cislo, 23 priloh, 22 cisel.

Prilohy by se mely vztahovat k cislu a ne k celemu rocniku ze?
Proc je tedy struktura takova, z tohoto nejde namapovat prilohy k cislum. Muzu to seradit tak, ze se v seznamu cisel rocniku periodika zobrazi nejdriv vsechna cisla a za ne vsechny prilohy. 
Tohle je ale zmatene, protoze uzivatel netusi k cemu ktera priloha vlastne je. Navic v API neni u priloh dodatecne info (jako u cisla: date, issueNumber, partNumber), je tam jen rozsireny title, ktery mi ani nedava moc smysl.

**Comment by LenkaDamborska** [comment]
Fakt? Tak to je nic moc, když tam není dodatečné info. To seřazení těch příloh je teď fakt chaos.. Konzultuju, jak by to zobrazení čísel a příloh mělo vypadat. Dám pak vědět. Jinak ty přílohy vycházely společně s číslem, ale jsou vlastně na stejné úrovni jak čísla. Obecně se značí, že jde o přílohu k ročníku/periodiku, která vycházela vedle běžných čísel.

**Comment by honza-rychtar** [comment]
Ano, jsou na stejne urovni jako cisla, ale jsou pevne svazany s cislem. Coz neni v datovem modelu zohledneno.

**Comment by LenkaDamborska** [comment]
Konzultovala jsem zobrazení příloh vyloženě u Brněnských novin a Brünner Zeitungu a spíš se jeví jako lepší varianta dát nejdřív čísla a pak přílohy. Třeba u Brünner zeitungu jsou uživatelé zvyklí hledat v číslech i přílohách zvlášť, takže v digitální podobě by jim to mělo dávat takto smysl. 
Takže ta struktura by mohla vypadat:

Ročník 1:
Čísla 1-⁠200
Příloha X 1-⁠200
Příloha Y 1-⁠200

Ročník 2:
Čísla 1-⁠200
Příloha X 1-⁠200
Příloha Y 1-⁠200

Ve stávajícím Krameriu by to bylo takto fajn, ale je fakt, že ty nemáš strukturu strom, ale karty, které se postupně načítají. To by uživatel skroloval dlouho, než by se dostal k poslední příloze..., ale asi mě teď nenapadá, jak to jinak udělat.

**Comment by zabak** [comment]
Musela by se prohodit úroveň ročníku a druhu, tj. po kliknutí na titul by uživatel nejprve vybral z karet "běžné vydání", "Příloha X", "Příloha Y" a pak teprve ročníky. Ale tohle je zase něco co by ideálně měl nabízet už server a ne vyrábět si až klient. Je to ale na základě existujících metadat vůbec  realizovatelné?

**Comment by LenkaDamborska** [comment]
Tak podle mě asi není. Zpracovává se to po ročnících. Každý ročník má pod sebou čísla a přílohy. Tak jsem to i myslela, aby to bylo po ročnících a uvnitř ročníku rozdělené na čísla a přílohy. Já chci, abychom to tak v Krameriu seřadili (myslím Brünner Zeitung a Brněnské noviny, ostatní periodika jsou jinak celkem v pohodě). Nebo ono to tak v Krameriu už je, jen ty přílohy jsou děsně proházené. Takže klient to dostane už seřazené a zobrazí to za sebou.

**Comment by zabak** [comment]
Já to myslel naopak než ty, tj. nejprve rozhodnout kterou chci přílohu, pak vidím její ročníky. Vlastně něco jako vícesvazkové dílo, kde každý svazek je samostatné periodikum.

**Comment by luckajirku** [comment]
Jen pro jistotu se vrátím k tomu, co Honzo píšeš výš (Prilohy by se mely vztahovat k cislu a ne k celemu rocniku ze). Pozor, existuje obojí (jak příloha k číslu, tak příloha k ročníku) a je třeba to rozlišovat. Příloha ročníku je na úrovni čísla, v NDK produkci jde o samostatný balíček s vlastním urn:nbn. Příloha k číslu je pod číslem v podstatě na úrovni stran.
Tady je vidět rozdíl:
příloha k ročníku: http://kramerius4.svkhk.cz/search/handle/uuid:ab0773a1-523f-4920-81e3-b3f5fa35fbaf
příloha k číslu: http://kramerius4.svkhk.cz/search/handle/uuid:91556d7e-dd21-4f74-94f6-318145eae7e2

**Comment by honza-rychtar** [comment]
Prilohy rocniku na urovni cisel jsou vyreseny - zobrazuji se mezi cisly, cisla i prilohy jsou serazeny podle data vydani.
Priklady z tohoto vlakna:
@LenkaDamborska http://www.digitalniknihovna.cz/mzk/periodical/uuid:10c38080-67bb-11e3-99ab-005056825209
@luckajirku http://www.digitalniknihovna.cz/svkhk/periodical/uuid:ab0773a1-523f-4920-81e3-b3f5fa35fbaf

Prilohy cisla, monografie, hudebnin ... na urovni stranek se zobrazuji v seznamu stranek na konci. Nahled je oznacen ikonou prilohy a v metadatech je u stranky uvedeno "Priloha"
@luckajirku http://www.digitalniknihovna.cz/svkhk/uuid/uuid:436f1d77-33b9-11e5-8f80-00155d010f03

**Comment by LenkaDamborska** [comment]
Fajn! :) Tlačítko (filtr) pro čísla a přílohy budeš řešit asi odděleně, předpokládám.

**Comment by honza-rychtar** [comment]
@LenkaDamborska jj #235
