### ISSUE TITLE
ve fasetach jsou periodika nazvane noviny

### ISSUE THREAD

**Issue by pavluska** [honza-rychtar/kramerius-web-client#214]
noviny je jenom cast periodik, periodika je souhrnny nazev pro noviny a casopisy a dalsi divnosti, co vychazely periodicky...

**Comment by honza-rychtar** [comment]
V ceskem prekladu budu pouzivat "Noviny a časopisy". Ve fasetach a jako tagy na kartach.
Je to stejne dlouhe jako "zvukové nahrávky", takze by to melo byt ok.
