### ISSUE TITLE
Čtení o T.G. Masarykovi - našeptávač

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#219]
Našeptávač při zadání dotazu:
čtení o t.g - našeptává
čtení o t.g. - už nenašeptává

Jak to? :)

**Comment by honza-rychtar** [comment]
Solr mi nevrati vysledky, kdyz je na konci retezce tecka pri pouziti wildcard.
Zaroven strasne dlouhou trva dotaz s mezerou na konci a wildcard.

U naseptavace budu ignorovat tecku a mezeru na konci dotazu. 
To muze davat v urcitych pripadech nekorektni vysledky, napr. 
hledani **čtení o t.g.** by naslo i **čtení o t.gm**
To je ale detail.

**Comment by LenkaDamborska** [comment]
Aha :) No, v našeptávači to až tak vadit nebude podle mě.

**Comment by honza-rychtar** [comment]
Opraveno v ramci opravy #293
