### ISSUE TITLE
Generování PDF - výběr stran

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#222]
Z uživ. testování: Výběr stran pro generování PDF - problém je číslování od 0 a dá se zvolit o jednu stranu navíc, která už v dokumentu není atp.

**Comment by honza-rychtar** [comment]
V aktualni verzi je jiny dialog pro generovani pdf nez ten v dobe testovani.
Ted uz zminene problemy nejsou.

**Comment by michalMZK** [comment]
Uvažuje se o přidání možnosti výběru určitých stran, které nejdou chronologicky za sebou? Buď by to mohlo být formou "zaškrtávání" vybraných stránek v náhledech v levém panelu, případně by se dalo přidat pole "výběr stran" do dialogu "Stáhnout jako PDF", resp. "Příprava k tisku".

Díky.

**Comment by honza-rychtar** [comment]
Pridam to jako moznost v dialogu pro pripravu k tisku/stahnout jako pdf.
Dal muzeme resit tady #251

**Comment by michalMZK** [comment]
Nejsem si jistý, jestli se tohle týká nové verze DK, nebo to tam takto bylo i dříve:

Funkce "**Příprava k tisku**" a "**Stáhnout jako PDF**" negeneruje přesně ty stránky, které si vyberu. Když např. u [tohoto titulu](http://www.digitalniknihovna.cz/mzk/uuid/uuid:87c36e60-550b-11e3-bc9f-5ef3fc9bb22f) zadám, že chci stránku 31, vygeneruje se strana 29. Ale týká se to všech knihy a evidentně to souvisí s těmi prvními stránkami, které mají zvláštní číslování. Obávám se, že to každému uživateli hned nedojde a nezačne si to sám od sebe přepočítávat, včera jsem to u nás řešil…

[Zaškrtávátko](https://github.com/honza-rychtar/kramerius-web-client/issues/222#issuecomment-256315810) nebude? :)

Díky!

**Comment by LenkaDamborska** [comment]
Já jsem to už s někým na studovně taky řešila. Vysvětlovala jsem, že číslo strany a index (číslo pořádí) jsou dvě jiné věci a že se to vybírá podle toho indexu, ale asi je to dost matoucí.
