### ISSUE TITLE
Filtr Nejnovější

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#223]
Filtr Nejnovější - jak naznačit, že jde o novinky v DK a ne o stáří dle roku vydání?

**Comment by honza-rychtar** [comment]
Zajimave, to mi vubec nedoslo :)
Myslis v hledani **RAZENI**, moznosti **Od nejnovejsich** a **od nejstarsich**?
Ono by slo radit podle obojiho, podle data vydani i podle data pridani do DK.
U data vydani je problem, ze udaj casto chybi, takze bych se do toho radeji nepoustel, protoze by razeni zahazovalo dokumentu - filtry to delat muzou, razeni urcite ne.
Takze jde o nejake rozumne prejmenovani.

**Comment by LenkaDamborska** [comment]
Jo, ano, Řazení - Od nejnovějších, Od nejstarších. Taky si myslím, že jde jen o to to rozumně pojmenovat. Když se řekne "nejnovější" nebo "novinky", někdo myslel, že jde o nové knihy na trhu. Ve starém Krameriu je taky Nejnovější.. Mělo by to být pak aspoň vysvětlené v nápovědě, pokud na nic nepřijdem...
