### ISSUE TITLE
Rušení filtrů

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#224]
Mělo by nové zadání dotazu do vyhledávacího pole anulovat filtry? Pokud ano, tak za jakých okolností? Je to vůbec možné? 
Člověk někdy chce omezit dotaz více filtry a měnit hodnotu pro fulltextové vyhledávání a jindy tam omezení už nechce a zapomíná filtry zrušit...

**Comment by honza-rychtar** [comment]
Filtry bych pri zmene hledaneho retezce v obrazovce hledani urcite nerusil. Uz jen kvuli tomu, ze obrazovka hledani slouzi i pro prochazeni konkretni sbirky - vybranim sbirky prejdu do obrazovky hledani s predvybranym filtrem pro sbirku. Kdyz pak menim hledany retezec, tak bych z te sbirky nechtel vypadnout, pokud tak neucinim sam explicitnim zrusenim filtru.

Nebo kdyz si omezim vysledky hledani jen na dokumenty v nemcine, tak chci dal vyhledavat jen v dokumentech v nemcine a ne to po kazdem dotazu omezovat znova.

Filtry jde rusit bud jednotlive nebo vsechny najednou.

**Comment by LenkaDamborska** [comment]
Ok. Tím pádem bude potřeba to uživatele naučit :) Jde o to pochopit systém filtrů.
