### ISSUE TITLE
Zobrazení dvoustran - stažení druhé strany

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#226]
Stažení konkrétní strany při zobrazení dvoustran - stáhne se ta první strana. Když chci druhou, musím přepnout zobrazení na jednostrany, kliknout na ni a stáhnout.

**Comment by honza-rychtar** [comment]
viz #227

**Comment by honza-rychtar** [comment]
Na to uz issue je #158
