### ISSUE TITLE
Ikonky PDF, TXT, JPG

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#227]
Z uživ. testování: Někdo měl problém s ikonkami PDF, TXT, JPG, že jsou dole a neviděl je. Nejdřív byly nahoře s ostatními ovládacími prvky, ale pak se daly dolů. Pamatuješ si, @honza-rychtar, proč jsi je dal jinam?

**Comment by honza-rychtar** [comment]
Mimo ovladaci prvky prohlizecky jsem je dal hlavne kvuli generovani pdf, ktere se vztahuje k celemu dokumentu a ne jen k otevrene strance. Ovladaci prvky se vztahuji jen k otevrene strance (strankam).

Dal bych stazeni jako akci do toolbaru pres standardni *download* ikonu vedle akce pro sdileni.
Potom by se objevil dialog s moznostma a vysvetlenim, napr. ze JPEG s originalem se otevre v novem tabu. Taky pri dvoustrankovem zobrazeni by se dala vybrat leva nebo prava.

OCR bych mohl vratit mezi ovladaci prvky, protoze to neni stazeni, nejedna se o obrazek, vztahuje se k aktulani strance a zobrazi se uvnitr aplikace (narozdil od jpg a pdf). Pokud by byla zobrazena dvoustranka, pak by se ocr zobrazilo pro levou i pravou stranu za sebou.

**Comment by LenkaDamborska** [comment]
Ano, to txt teoreticky patří vedle ovládacích prvků.. Ale přemýšlím, že v tom toolbaru je to trochu oddělené od prohlížečky, ne? Jestli tohle není jen o zvyku... Možná by stačilo to JPG a PDF jen nějak zvýraznit a nechat to dole.

**Comment by dominikmatus** [comment]
K tomu, nefunguje mi vytváření PDF u publikací z MZK.

**Comment by honza-rychtar** [comment]
@dominikmatus Ktery dokument konkretne a jaky rozsah stran?

**Comment by dominikmatus** [comment]
Například http://www.digitalniknihovna.cz/mzk/view/uuid:4f4e2d98-a1a7-4bfd-bd47-213ae44b8507?page=uuid:143ae528-02d8-4713-a34f-726f21931932

**Comment by honza-rychtar** [comment]
Zkousel jsem prvni stranu a prvnich 10 stran a funguje to.
Cely dokument ma pres 700 stran, to by trvalo dlouho a taky ma MZK limit na 300 stran - tohle jeste neni v klientovi zohledneno, pridam kontrolu na limit nastaveny v konkretnim Krameriovi.
Kolik stran jste zkousel? Funguje vam stazeni pres odkaz http://kramerius.mzk.cz/search/api/v5.0/pdf/selection?pids=uuid:143ae528-02d8-4713-a34f-726f21931932 (prvni strana toho dokumentu)?

**Comment by dominikmatus** [comment]
To vím, přes krameria jsem si stál prvních 300 stran. Ale stáhnout zbytek nejde, pokud ty další strany nezaškrtnu ručně, což je nepraktické. Proto jsem zkusil digitální knihovnu, kde jde vybrat rozmezí. Ale nefunguje to.

**Comment by honza-rychtar** [comment]
A jeke rozmezi jste teda zkousel?
Funguje vam vygenerovani jen jedne strany?
Pokud ne, jaky pouzivate prohlizec?

**Comment by dominikmatus** [comment]
Už mi to na digitální knihovně funguje, ale pokud zadám rozmezí, tak mi to přes 150 stránek nevygeneruje. Požívám Chrome.

**Comment by dominikmatus** [comment]
Ideální by bylo, pokud to zpracovává nějaký server, to stáhnout v několika dávkách a spojit to do celku aby to fungovalo i přes limit 300 stran. Ale tak chápu omezení.

**Comment by honza-rychtar** [comment]
Tak uz vim, kde je pro problem.
Rozsah stran se zadava explicitnim vyjmenovanim identifikatoru stranek v URL, coz v pripade cca 160 stran a vice presahne limit pro delku URL.
Daval jsem kdyzi pozadavek, aby slo pres Krameria zadat rozsah urcenim indexu prvni strany a poctem stran.
Zjistim jestli uz to funguje a v digitalni knihovne to upravim.

Generovani PDF zpracovava Kramerius a limit poctu stran si urcuje kazda kvnihovna ve svem Krameriovi. 
MZK mivala limit pres tisic stran, nevim proc ho snizili.

**Comment by dominikmatus** [comment]
Mohli by omezit zátěž serveru jednoduše tak, že budou mít v PDF celé knihy rovnou na stažení. Nějaké tendence vyhnout se komerčnímu využití a podobné nesmysly u volných děl nechápu. Ale to tu nebudeme řešit. Budu rád, když to spravíte. Digitální knihovna je super. Už jen aby Národní knihovna zprovoznila normální kramerius, který nebude tak otravný, že mě donutí si radši knihu přečíst v knihovně.

**Comment by michalMZK** [comment]
Zdravím, generování pdf celých knih nebo většího rozsahu stran pořád nefunguje, máme nějaké nové informace? :) Děkuji,MŠ

**Comment by honza-rychtar** [comment]
Generovani je omzeno na 150 stran. Pokud ma knihovna nastavena pro sveho Krameria nizsi limit, tak se pouzije ten.
Generovani pdf pres API i pres localPrintPDF endpoint pouzity pri tisku v K4 klientovi a ted i v Digitalni knihovne pres "Priprava k tisku" prebiraji seznam uuid stranek pres parametr v url. Delka url je omezena, takze pres 150 stranek se tam nevleze.
S timto nic neudelam. Ted uz se to aspon pri vyberu stranek kontroluje na prekroceni limitu a zobrazuje se i limit vybrane knihovny (pokud je nizsi nez 150).

Puvodne bylo issue o tlacitkach PDF, JPEG, TXT. Tlacitka jsou zrusena a akce jsou presunuty do toolbaru.
Issue zaviram.
