### ISSUE TITLE
Zobrazování úryvků textů s hledaným výrazem (snippets)

### ISSUE THREAD

**Issue by michalMZK** [honza-rychtar/kramerius-web-client#228]
Pokud dohledaný dokument obsahuje OCR, úryvek plného textu se zvýrazněným hledaným výrazem se zobrazuje pouze u periodik, nikoliv u knih. Klient od Incadu (5.2.0) text zobrazuje i u monografií, takže to bude spíš souviset se způsobem zobrazení výsledků vyhledávání, než s autorskými právy…
Děkuji.

**Comment by honza-rychtar** [comment]
Z vysledku fulltextoveho hledani se v pripade periodik prejde do seznamu stranek i se snippetem s hledanym retezcem. V pripade monografii tato meziuroven neni potreba, prejde se rovnou do prohlizecky s touto monografii, kde se stranky vyfiltrujou pouze na ty, ktere obsahuji hledany reteze a ten se pak zvyrazni primo na strankach monografie pres obdelnik v obrazku stranky - k tomuto zvyrazneni je potreba, aby monografie obsahovala nejen OCR ale take ALTO.

**Comment by michalMZK** [comment]
Díky, ale v případě, že uživatel nemá přístup do plného obsahu, tak je bohužel u monografií o snippety ochuzen, škoda.

**Comment by honza-rychtar** [comment]
To ano, ale je otazka, zda by mely byt vubec snippety u neverejnych dokumentu pristupne (a jak by mely/mohly byt dlouhe), ono takto jde postupnym posunem snippetu ziskat text cele strany.

**Comment by zabak** [comment]
Logické omezení je nejít za hranici jedné věty. Pak nevíš, kam se posouvat.

**Comment by honza-rychtar** [comment]
Funguje to tak, ze se bera delka snippetu (pouzivam 120 znaku). Cely text se rozkouskuje na tyto casti a pri zadani libovolne castu textu ze snippetu to vrati zase stejny snippet, takze neni mozne ze znalosti snippetu ziskat text pred nebo za.
