### ISSUE TITLE
Částečně veřejný dokument

### ISSUE THREAD

**Issue by PavlinaDolezalova** [honza-rychtar/kramerius-web-client#232]
V přehledu veřejných dokumentů se nezobrazuje i ten, který je veřejný částečně. Případ SVK PK a titul  Plzeňské listy 1875-1911, u kterého máme roky 1875-1890 volné (http://www.digitalniknihovna.cz/svkpk/uuid:3da220d0-6b98-11de-9ebf-000d606f5dc6)

**Comment by honza-rychtar** [comment]
Cele periodikum **Plzeňské listy** (http://www.digitalniknihovna.cz/svkpk/periodical/uuid:3da220d0-6b98-11de-9ebf-000d606f5dc6) je oznaceno jako private.
DC: http://k4.svkpl.cz/search/api/v5.0/item/uuid:3da220d0-6b98-11de-9ebf-000d606f5dc6/streams/DC
`<dc:rights>policy:private</dc:rights>`
Odtud to prebira SOLR, pres ktery se filtrovane vysledky ziskaji.

K4 s filtrem na verejne dokumenty taky periodikum nezobrazi - http://k4.svkpl.cz/search/r.jsp?forProfile=search&forProfile_sorting_dir=&fq=dostupnost%3A%22public%22&debug=&sort=&q=&issn=&title=&keywords=&author=&rok=&udc=&ddc=

**Comment by PavlinaDolezalova** [comment]
OK, díky za vysvětlení.
