### ISSUE TITLE
Žánr - vyhledávání a pojmenování

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#239]
Předávám dotaz kolegů: Je možné při vyhledávání hledat i v jiných polích záznamu (např. v genre - žánr)? V klíč. slovech klient (prý) prohledává, žánr je ale často přesnější, co se týče typu díla.
Otázka, jak moc by to ovlivnilo výsledky vyhledávání...

A druhá věc: Bylo by možné přejmenovat v podrobnostech ŽÁNR na ŽÁNR/FORMA?

**Comment by honza-rychtar** [comment]
> Je možné při vyhledávání hledat i v jiných polích záznamu (např. v genre - žánr)? 

Zanr neni v Solr, takze vyhledavat/prochazet podle nej nejde.
Napr. tento dokument http://www.digitalniknihovna.cz/mzk/uuid/uuid:58945553-4def-4f9b-93e6-54663ad6d7fe
Ma vyplneny zanr. 
V MODS: http://kramerius.mzk.cz/search/api/v5.0/item/uuid:b8369227-e7ea-4355-a848-086eccd4e46f/streams/BIBLIO_MODS
Pole **genre** s obsahem *grafické listy*
V Solr: http://kramerius.mzk.cz/search/api/v5.0/search?q=PID:%22uuid:b8369227-e7ea-4355-a848-086eccd4e46f%22
Toto pole neni.

> V klíč. slovech klient (prý) prohledává, žánr je ale často přesnější, co se týče typu díla.

"žánr je ale často přesnější" - co znamena casto? Najit dokument s vyplnenym zanrem je ted fakt slozite, malo ktery dokument toto pole ma. Na druhou stranu klicova slova jsou bezne vyplnena.
U tech novych grafik uz zanr byva "casteji" (neresil tu pripominku nekdo okolo tech grafik? :))

Kvuli absenci zanru v Solr se ani nemuzu podivat jak a na co ruzne knihovny toto pole pouzivaji.
Kazdopadne jsem pro, aby se pole do solr pridalo. Pak muzu pridat prochazeni podle zanru, filtrovani podle zanru (fasety) a pripadne i vyphledavani podle zanru.

> A druhá věc: Bylo by možné přejmenovat v podrobnostech ŽÁNR na ŽÁNR/FORMA?

Pro koho? Je to **uzivatelske** rozhrani. Mozna se pletu, ale tohle mi pripada jako puntickarske dodrzovani technickeho nazvoslovi pro katalogizatora. Uzivatel z toho bude spis zmateny - ja teda jsem :)

**Comment by pavluska** [comment]
Zdravim,

chceme dalsiho klienta pro knihovniky? :) Nazory knihovniku je v takovychto
pripadech fakt ignorovat, resp. overit v praxi s realnymi uzivateli mimo
knihovnicke prostredi. On to neni blby napad, ale kvuli 15 knihovnikum to
obvykle neni idealni z pohledu pomeru cena - vykon. Nehlede na to, ze
vetsina zaznamu toto pole mit nebude nebo je pouze v katalogu a konverzi se
do MODS nedostalo, coz pak spis mate uzivatele, kdyz si mysli, ze jina
literatura daneho zanru se v digitalni knihovne nevyskytuje.

S pozdravem,
Pavla

PS: Uz radsi neberu v potaz ani sebe, protoze jsem moc ovlivnena vsema tema
monografiema, periodikama, signaturama...  :)

Dne čt 9. 6. 2016 15:48 uživatel Jan Rychtář <notifications@github.com>
napsal:

**Comment by LenkaDamborska** [comment]
Jej, vidím, že jsem neodpověděla. Vyřídila jsem v MZK.

**Comment by honza-rychtar** [comment]
Zaviram, zanr neni v Solr, nemuzu pres nej filtrovat/hledat.
