### ISSUE TITLE
Nezobrazovat hřbety coby reprezentativní stránky

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#245]
http://www.digitalniknihovna.cz/kfbz/

pokud je první obrázek označený jako hřbet, tak zobrazit jako náhled až druhý obrázek.

**Comment by honza-rychtar** [comment]
To bych strasne rad, ale **nemuzu** to ovlivnit. Ve vybranych nebo vysledcich hledani dostanu cele dokumenty, ze kterych zobrazuju obrazek, ktery ma kramerius asociovany s uuid dokumentu. Pokud bych mel zobrazovat jine stranky, tak bych se musel pro kazdy dokument zeptat na vsechny potomky a pak nejakou heurestikou vybrat reprezentanta sam - coz by bylo silene pomale a neefektivni.

Tohle jsme resili uz mockrat tady a po mailech.
Kramerius by mel umet nastavit pro dokument (nebo jeho cast) reprezentujici stranku (nahled dokumentu). Resi se to uz dlouho a je to celkem pozadovana a logicka funckionalita. 
Nahled dokumentu by mel jit nastavit manualne (vybranim libovolne stranky dokumentu v editoru) a taky programove - pustil by se skript, ktery projde vsechny dokumenty a jako nahled nastavi prvni stranu, ktera neni hrbet nebo prazdna strana. Nebo muze za nahled zvolit stranku typu *TitlePage* (pokud existuje).
Pokud nahled vybrany nani, tak se pouzije prvni stranka jako je to ted.

Na tomhle nevidim nic sloziteho, jen to musi nekdo zadat jako rozsireni Krameria.
Je to pak pouzitelne pro vsechny klienty a dava to knihovnam moznost si nahled zvolit. Taky odpadnou hacky jako umele zvoleni 8. stranky dokumentu do vybranych, protoze je to zrovna pekna stranka.
