### ISSUE TITLE
našeptávač a řazení

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#246]
Na začátku našeptaného seznamu by měly být výsledky kde hledaný text je na začátku a pak teprve ty ostatní, seřazené nejlépe podle vzdálenosti hledaného textu od začátku názvu.

Viz též https://github.com/moravianlibrary/kramerius-for-ios/issues/135

**Comment by LenkaKravecova** [comment]
Zkouším a jde to tak, jak píšeš. Můžeme zavřít?

**Comment by zabak** [comment]
ano
