### ISSUE TITLE
Prepinace u periodika

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#247]
Filtrovani - vse, pouze prilohy, pouze cisla
Zobrazeni - mrizka, seznam (bez nahledu), kalendar (do konce roku)
Razeni - od nejnovejsich, od nejstarsich

**Comment by LenkaDamborska** [comment]
O tohle stále stojíme :)

**Comment by honza-rychtar** [comment]
Zaviram. 
Zobrazeni je hotovo.
Filtrovani dal resi #235 
Razeni dal resi #306
