### ISSUE TITLE
Stránka je "moc dlouhá" a nejsou vidět ikony TXT, PDF

### ISSUE THREAD

**Issue by black23** [honza-rychtar/kramerius-web-client#249]
Po posledním updatu jení možné využít zobrazení přepisu a generování PDF, protože ikony nejsou vidět. Testováno na několika různých OS a rozlišeních.
http://prntscr.com/czaf0c

**Comment by black23** [comment]
Super, díky za info. Nicméně není možné rolovat až dolů a není vidět celý text popisku v pravé části stránky.

**Comment by honza-rychtar** [comment]
Aha, opravim. Diky. #250
