### ISSUE TITLE
Štítek Stránka na kartách ve 4 řadách

### ISSUE THREAD

**Issue by LenkaKravecova** [honza-rychtar/kramerius-web-client#254]
Štítek Stránka a Noviny a časopisy nejsou vidět celé (resp. ten text), když jsou karty ve čtyř řadách. Vypadá to takto: 
![noviny_stranka](https://cloud.githubusercontent.com/assets/11834597/20107005/5023cc78-a5d7-11e6-9374-04d89dd51a5e.jpg)

Ve 3 řadách už je to ok.

**Comment by honza-rychtar** [comment]
No kdyz se tam nevleze text cely, tak se pridaji ty 3 tecky.
A asi radeji takto, nez i pri velke sirce prohlizece zobrazovat min sloupcu.
