### ISSUE TITLE
Dokument v PDF - pouze sudé nebo liché strany

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#255]
U dokumentů v PDF se zobrazují buď jen liché strany nebo sudé strany. Tady např. jen sudé: http://www.digitalniknihovna.cz/mzk/view/uuid:3621340c-a8ae-4f12-8f4d-47021270ddf0 (v Krameriu jsou určitě všechny strany). Nebude to problém související s jedno/dvoustránkovým zobrazením?

**Comment by honza-rychtar** [comment]
Je to tim. Kdyz si stranku nactu v mensim okne, kdy je vychozi jednostrankove zobrazeni, tak se strankuje po jedne.
Tu pdf prohlizecku predelam uplne. Ta je hodne stara, jsou tam jeste puvodni ovladaci prvky atd.

**Comment by honza-rychtar** [comment]
Je pouzita nova PDF prohlizecka. Zatim funguje samostatne bez vetsi interakce se zbytkem aplikace. Metadata, hledani, sdileni apod. funguje normalne, ale stazeni, hledani uvnitr dokumentu, prechod na dalsi/predchozi stranku, zoom, rotace se resi uvnitr prohlizecky.

Priklad:
http://www.digitalniknihovna.cz/mzk/uuid/uuid:4873e8c7-5967-4003-8544-96f64ca55da7
