### ISSUE TITLE
Hláška o nepřístupnosti dokumentu - Více informací

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#257]
V hlášce by měly být informace podle toho, co má každá knihovna v Krameriu. Asi už jsme to kdysi řešili.. My tam máme např. že k dokumentu se člověk dostane na studovnách MZK. To by tam chtělo dát. 

https://github.com/honza-rychtar/kramerius-web-client/issues/83

**Comment by honza-rychtar** [comment]
Pridam to tam. To neni problem, jen mi delaji starosti 3 veci:
1. Vetsina knihoven tam ma defaultni hlasku "Tento dokument není veřejně přístupný."
2. Knihovny jsou v psani vlastni hlasky velice vynalezave, zejmena co se formatovani tyce. Napr. nadpis resi kazdy jinak, h1, h3, b, nic, ...
Vypada to pak hodne nekonzistentne.
3. Nekdo pridava inline styly, ktere maji nejvyssi prioritu a prebiji tak vse ostatni, napr. font color nastavi na cernou, coz vede k tomu, ze je pak cerny text na tmavem pozadi v klientovi ...

No nic, nejak to vyresim. Nejspis to stylovani uplne zrusim.
Ono je potreba si uvedomit pri psani tech textu (info i rightMsg), ze uz se to nepise jen pro K4 klienta, ale pro 5 ruznych klientu - K4, K5, DK, Android, iOS, takze:
A) Nemelo by se pouzivat specificke stylovani - klienti maji ruzne barvy, fonty, velikosti, ...
B) Nemelo by se primo odkazovat do konkretniho klienta
C) Na vsechny zdroje (napr. obrazky) by se melo odkazovat absolutne - pri relativnim odkazovani se obrazek muze zobrazit v K4, ale jinde se to nechytne
D) Text by nemel byt prilis specificky pro konkretniho klienta.

**Comment by LenkaDamborska** [comment]
@honza-rychtar, na toto jsem zapomněla na schůzce. Souhlas. Patří to mezi ty základní věci pro orientaci uživatelů. Dnes zas někdo volal na PR a nechápal, proč je dokument neveřejný a co má dělat. Kdyby tam byl ten náš text z Krameria, tak by nám to moc pomohlo.

**Comment by MartinRumanek** [comment]
Aha, nepostřehl jsem, že už je tu existující issue :-)

Z pohledu API ti můžu nějak pomoct? Minimálně můžeme změnit defaultní hlášku v Krameriu.

**Comment by honza-rychtar** [comment]
Hotovo.
V dialogu o nedostupnem dokumentu pribyla sekce 
**Upřesňující informace zdrojové knihovny**
Pod timto je nazev zdrojove knihovy.
A pod tim samotny text z API info rightMsg.
rightMsg text osekavam o ruzne formatovaci tagy a prebijim styly.
Protoze napr. <a …><u><i><big>Více informací …..</u></i></big></a> fakt nee :)

V tom rightMsg se nema resit forma, ale obsah. H, P, A bohate staci.

**Comment by LenkaDamborska** [comment]
Díky. Trochu jsem upravila náš text, ať se tam neopakují některé informace.
