### ISSUE TITLE
Periodika - rozsah roků vydání

### ISSUE THREAD

**Issue by svetlym** [honza-rychtar/kramerius-web-client#258]
Při zobrazení seznamu titulů se u periodik importovaných z K3 zobrazuje například:

Česká Thalia
1887-1882

zatímco u periodik importovaných z PSP balíku vytvořeného Proarcem se zobrazuje pouze počáteční rok vydávání:

Dalibor
1879

Je to tím, že v Siriovi (editor K3 formátu) byla jen jedna položka pro datum vydání a proto se do ni vyplňoval rovnou rozsah, konkrétně:

`
<mods:dateIssued>1892-1895</mods:dateIssued>
`

Zatímco v PSP jsou údaje pro začátek a konec vydávání:

```
<mods:dateIssued point="start">1879</mods:dateIssued>
<mods:dateIssued point="end">1927</mods:dateIssued>
```

Bylo by možné v obou případech zobrazovat rozsah začátek-konec?

**Comment by honza-rychtar** [comment]
Tento udaj se bere ze solr, konkretne pole datum_str. 
U periodika Dalibor - http://kramerius4.mlp.cz/search/api/v5.0/search?q=PID:%22uuid:fd221699-0dd2-4a4f-9aea-609097a5132a%22 
je datum_begin = detum_end = datum _str = 1879
V DC datum chybi uplne - http://kramerius4.mlp.cz/search/api/v5.0/item/uuid:fd221699-0dd2-4a4f-9aea-609097a5132a/streams/DC

Pro srovnani Česká Thalia
Solr: http://kramerius4.mlp.cz/search/api/v5.0/search?q=PID:%22uuid:1dba7980-4e04-11df-930a-0030487be43a%22
datum_begin = 1887
datum_end = 1892
datum_str = 1887-1892
DC: http://kramerius4.mlp.cz/search/api/v5.0/item/uuid:1dba7980-4e04-11df-930a-0030487be43a/streams/DC
date = 1887-1892

Mate pravdu, ze k problemum dochazi tam, kde je dateIssued v MODS rozdeleno na start a end.
Dival jsem se na data z MZK a NKP, kde to maji rozdeleno taky, ale jim to funguje.
Oni ale maji krom start a end vyplneno take cele datum - dateIssued maji 3x:

```
<mods:dateIssued>XXXX-YYYY</mods:dateIssued>
<mods:dateIssued point="start">XXXX</mods:dateIssued>
<mods:dateIssued point="end">YYYY</mods:dateIssued>
```

**Comment by svetlym** [comment]
Díky za odpověď.

Je jasné, že když ten údaj neposkytuje SOLR, tak se s tím v klientovi nedá nic dělat. Tudíž tuhle issue zavírám.
