### ISSUE TITLE
Klient se nenačítá - Chrome Verze 55

### ISSUE THREAD

**Issue by vojtisev** [honza-rychtar/kramerius-web-client#259]
V Chrome se nenačte obsah:

![k4_chrome](https://cloud.githubusercontent.com/assets/11600358/21011514/eea72ac0-bd51-11e6-8a79-834e282a8957.png)

Ve FF to funguje správně.

**Comment by honza-rychtar** [comment]
www.digitalniknihovna.cz vam v Chrome funguje?
Podle toho screenshotu to vypada, ze se nenacte ani samotny framework (podle address baru).
Zkuste F5 F5 F5
Pokud nepomuze, tak prosim o vypis konzole 
Windows/Linux: Ctrl+Shift+J 
Mac: Cmd+Opt+J

**Comment by vojtisev** [comment]
digitalniknihovna.cz se chovala stejně, i po CTRL+F5. Záhada je, že dnes mi to běží, aniž bych cokoliv dělal jinak. Pokud na to narazím znovu, pošlu výpis konzole. Díky.

**Comment by vojtisev** [comment]
Narazil jsem na stejný problém, log:

> Uncaught Error: [$injector:modulerr] Failed to instantiate module KrameriusClient due to:
Error: [$injector:modulerr] Failed to instantiate module angular-google-analytics due to:
Error: [$injector:nomod] Module 'angular-google-analytics' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.8/$injector/nomod?p0=angular-google-analytics
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:68:12
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:2082:17
    at ensure (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:2006:38)
    at module (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:2080:14)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4617:22
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:321:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4601:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4618:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:321:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4601:5)
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=angular-google-analytics&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'angular-google-analytics'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.8%2F%24injector%2Fnomod%3Fp0%3Dangular-google-analytics%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A2082%3A17%0A%20%20%20%20at%20ensure%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A2006%3A38)%0A%20%20%20%20at%20module%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A2080%3A14)%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4617%3A22%0A%20%20%20%20at%20forEach%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4601%3A5)%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4618%3A40%0A%20%20%20%20at%20forEach%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4601%3A5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:68:12
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4640:15
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:321:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4601:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4618:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:321:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4601:5)
    at createInjector (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4523:19)
    at doBootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:1758:20)
    at bootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:1779:12)
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=KrameriusClient&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20angular-google-analytics%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'angular-google-analytics'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.8%2F%24injector%2Fnomod%3Fp0%3Dangular-google-analytics%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A2082%3A17%0A%20%20%20%20at%20ensure%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A2006%3A38)%0A%20%20%20%20at%20module%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A2080%3A14)%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4617%3A22%0A%20%20%20%20at%20forEach%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4601%3A5)%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4618%3A40%0A%20%20%20%20at%20forEach%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4601%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.8%2F%24injector%2Fmodulerr%3Fp0%3Dangular-google-analytics%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'angular-google-analytics'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.5.8%252F%2524injector%252Fnomod%253Fp0%253Dangular-google-analytics%250A%2520%2520%2520%2520at%2520https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A68%253A12%250A%2520%2520%2520%2520at%2520https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A2082%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A2006%253A38)%250A%2520%2520%2520%2520at%2520module%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A2080%253A14)%250A%2520%2520%2520%2520at%2520https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A4617%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A321%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A4601%253A5)%250A%2520%2520%2520%2520at%2520https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A4618%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A321%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A4601%253A5)%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4640%3A15%0A%20%20%20%20at%20forEach%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4601%3A5)%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4618%3A40%0A%20%20%20%20at%20forEach%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4601%3A5)%0A%20%20%20%20at%20createInjector%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4523%3A19)%0A%20%20%20%20at%20doBootstrap%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A1758%3A20)%0A%20%20%20%20at%20bootstrap%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A1779%3A12)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:68:12
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:2082:17
    at ensure (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:2006:38)
    at module (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:2080:14)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4617:22
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:321:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4601:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4618:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:321:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4601:5)
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=angular-google-analytics&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'angular-google-analytics'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.8%2F%24injector%2Fnomod%3Fp0%3Dangular-google-analytics%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A2082%3A17%0A%20%20%20%20at%20ensure%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A2006%3A38)%0A%20%20%20%20at%20module%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A2080%3A14)%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4617%3A22%0A%20%20%20%20at%20forEach%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4601%3A5)%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4618%3A40%0A%20%20%20%20at%20forEach%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4601%3A5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:68:12
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4640:15
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:321:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4601:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4618:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:321:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4601:5)
    at createInjector (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4523:19)
    at doBootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:1758:20)
    at bootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:1779:12)
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=KrameriusClient&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20angular-google-analytics%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'angular-google-analytics'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.8%2F%24injector%2Fnomod%3Fp0%3Dangular-google-analytics%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A2082%3A17%0A%20%20%20%20at%20ensure%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A2006%3A38)%0A%20%20%20%20at%20module%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A2080%3A14)%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4617%3A22%0A%20%20%20%20at%20forEach%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4601%3A5)%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4618%3A40%0A%20%20%20%20at%20forEach%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4601%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.8%2F%24injector%2Fmodulerr%3Fp0%3Dangular-google-analytics%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'angular-google-analytics'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.5.8%252F%2524injector%252Fnomod%253Fp0%253Dangular-google-analytics%250A%2520%2520%2520%2520at%2520https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A68%253A12%250A%2520%2520%2520%2520at%2520https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A2082%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A2006%253A38)%250A%2520%2520%2520%2520at%2520module%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A2080%253A14)%250A%2520%2520%2520%2520at%2520https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A4617%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A321%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A4601%253A5)%250A%2520%2520%2520%2520at%2520https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A4618%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A321%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.5.8%252Fangular.js%253A4601%253A5)%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4640%3A15%0A%20%20%20%20at%20forEach%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4601%3A5)%0A%20%20%20%20at%20https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4618%3A40%0A%20%20%20%20at%20forEach%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4601%3A5)%0A%20%20%20%20at%20createInjector%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A4523%3A19)%0A%20%20%20%20at%20doBootstrap%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A1758%3A20)%0A%20%20%20%20at%20bootstrap%20(https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A1779%3A12)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:68:12
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4640:15
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:321:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4601:5)
    at createInjector (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4523:19)
    at doBootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:1758:20)
    at bootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:1779:12)
    at angularInit (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:1664:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:31763:5
    at HTMLDocument.trigger (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:3207:7)

**Comment by honza-rychtar** [comment]
Opraveno, viz #261
Prosim o kontrolu.
