### ISSUE TITLE
Hledání bez diakritiky

### ISSUE THREAD

**Issue by MartinRumanek** [honza-rychtar/kramerius-web-client#260]
Kramerius 5.3.5 začal podporovat SOLR6 a má teď lepší podporu češtiny (možnost vyhledávat bez diakritiky a podporu pro STOP slova).

Momentálně má přemigrováno pouze [Městská knihovna Česká Třebová](http://digiknihovna.cz)

V K5 i přes API můžu vyhledat slovní spojení "Michaela Stranska", ale v klientovi to nefunguje.

http://k5.digiknihovna.cz/search/api/v5.0/search?q=Michaela%20Stranska

**Comment by LenkaKravecova** [comment]
Už je to ok.
