### ISSUE TITLE
Nezobrazení webu při použití uBlock

### ISSUE THREAD

**Issue by zdenekhruska** [honza-rychtar/kramerius-web-client#261]
Při zapnutém uBlock Origin (v. 1.10.4) se v Google Chrome (v. 55.0.2883.87 m) i v Mozilla Firefox (v. 50.1.0) nezobrazí www.digitalniknihovna.cz, ale zobrazí se jen šedá stránka (viz screenshot). 
![ublock](https://cloud.githubusercontent.com/assets/20533302/22283805/71802340-e2e4-11e6-8e85-31696353edd1.png)

**Comment by LenkaDamborska** [comment]
Potvrzuji toto chování z jiného zdroje :)

**Comment by MartinKravec** [comment]
Me 2

**Comment by vojtisev** [comment]
Není to stejný problém, jako #259 (používám adblock)?

**Comment by honza-rychtar** [comment]
Opraveno, prosim o potvrzeni.
Bylo to kvuli AdBlocku.

Digitalni knihovna zadne reklamy neobsahuje. Problem byl v Google Analytics, resp. v AdBlocku, resp. ve vas, co AdBlock pouzivate.

AdBlocky blokuji ruzne zdroje, napr. vse ve co obsahuje google-analytic.
Modul pro Google Analytics pro Angular (Framework, ve kterem je Digitalni knihovna napsana) se nacital z angular-google-analytics.min.js a vase AdBlocky ho blokovaly. Angular takto nenastartuje, protoze mu chybi jeden z deklarovanych modulu. Coz je dobre, protoze to hlida chyby u me a ja nepredpokladam, ze mi nekdo na pozadi upravuje obsah stranek, prepisuje tagy a blokuje skripty. A pokud to nekdo dela, tak je mi to uprimne uplne jedno, ze mu pak aplikace nefunguje. Pouzivani AdBlocku je proste spatne, ale moralizovat tady nebudu :)

**Comment by vojtisev** [comment]
Je to v pořádku.
