### ISSUE TITLE
Výřez obrázku k tisku

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#266]
Toto byl nápad někoho ze zaměstnanců. Hodí se např. u článků, vyberu část obrázku, kterou bude možné vytisknout. Nevím, zda jsme o tomto diskutovali. Ať se případně vyjádří i ostatní, co si o tom myslí.

**Comment by honza-rychtar** [comment]
Vyrezy jsme resili, ze budeme pouzivat IIIF. #269 
Nebude se to tykat primo tisku, ale vyrez obrazku se bude otevirat v novem tabu jako JPEG, ktery pujde poslat na tiskarnu rovnou z prohlizece.
