### ISSUE TITLE
dateOther do Podrobností

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#267]
Pokud je v MODS dateOther, tak i tento údaj zobrazovat v Podrobnostech. U některých starých tisků se to může objevit (jde o datum produkce, to se převádí do dateOther).

**Comment by honza-rychtar** [comment]
Prosim o nejake priklady pro testovani

**Comment by LenkaDamborska** [comment]
Třeba tady je v MODS pouze dateOther (originInfo): http://www.digitalniknihovna.cz/mzk/view/uuid:83c035ec-c5f4-4e8e-b945-56ecdf2d0e06

**Comment by honza-rychtar** [comment]
Udelal jsem to tak, ze pokud neni vyplneno "klasicke" datum v dateIssued, tak se pouzije dateOther (pokud je).
Takze treba ten uvedeny odkaz - ted se to chova, jako by datum bylo vyplneno v dateIssued.
Muze to byt takto?

Nemuzu to pouzit jako dalsi atribut "datum produkce" - musi to byt soucasti nakladatelskych udaju, protoze je to zanoreno pod originInfo, ktere je opakovatelne.
Pripadne se to da pouzit jako dalsi cast nakladatelskych udaju. Ty jsou ted ve formatu:
[MISTO]: [NAKLADATEL], [DATUM VYDANI]
A za to muzu pridat ("datum produkce" [DATUM PRODUKCE])

Jsou pripady, ze je vyplneno dateIssued a zaroven je vyplneno dateOther?

**Comment by zabak** [comment]
@LenkaDamborska můžeš odpovědět?

**Comment by honza-rychtar** [comment]
Ono je to fuk. dateOther se pouzije jen pokud je vyplnene a zaroven neni vyplnene dateIssued.
Podle MODS specifikace je dateOther = "A date that does not fall into another category but is important to record."
Takze ho stejne nemuzu pouzit jako nejake konkretni jine datum (v tomto pripade datum produkce).
