### ISSUE TITLE
Nevyhledá se zadaný rok vydání u periodika

### ISSUE THREAD

**Issue by pavluska** [honza-rychtar/kramerius-web-client#274]
Dotaz z fb: Zadám hledaný výraz, vyberu rok vydání a objeví se mi nalezené materiály. Při rozkliknutí jednotlivých novin se mi však objevují zprávy mimo výběr rok vydání. Např. http://www.digitalniknihovna.cz/mzk/search/?sort=relevance&accessibility=public&doctypes=periodical&from=1899&to=1899&q=demokracie

Navíc nesedí "počet výskytů" s reálným výsledkem po rozkliknutí

**Comment by zabak** [comment]
Přijde mi že je problém že se nepřenáší do stránky s výsledky původní nastavení filtrů ale jen dotaz. Takže při vstupu na "mezistránku" se snippety už systém neví, že tam byl časové omezení. Takže by bylo potřeba přenášet časové omezení - asi nejen na stránku s výsledky, ale pak i do prohlížení jednotlivé stránky, aby se informace zachovala i při návratu do výsledků vyhledávání. Mám pravdu?

**Comment by LenkaKravecova** [comment]
Toto už asi není aktuální nebo aspoň já ten problém u sebe nemám.
