### ISSUE TITLE
Na mobilu se nezobrazují fasety

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#278]
Nevím, jak moc toto řešit, ale když se někdo dívá na digitalniknihovna.cz na mobilu, tak jsou ty fasety nějak potlačené. To by asi chtělo přizpůsobit, i když je appka.

**Comment by honza-rychtar** [comment]
V nove verzi (0.4.9) pribyla optimalizace pro mobilni zarizeni, kde uz je mozne na mobilnich zarizenich zobrazovat filtry u hledani a prochazeni a vyhledavat pres lupu v toolbaru.
