### ISSUE TITLE
Hledání fulltextu v periodiku a omezení na roky

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#294]
Hledám "plánička" v celé dig. knihovně. Omezím výsledky jen třeba na rozmezí 1933-1934. Najdu v seznamu výsledků Lidové noviny. Zobrazí se mi seznam výsledků v celých lidových novinách ale mě zajímají jen výsledky z let 1933-1934, tam ale musím poměrně dlouho scrollovat.

**Comment by zabak** [comment]
Toto už řeší #274 ale je tam ještě ta část "poměrně dlouho scrollovat". Pokud nezadám časové omezení dopředu, tak nemám možnost ho zadat ani v rámci snippetů periodika. Tj. od určitého počtu výsledků (třeba 12 nebo 24) by to chtělo přejít na zobrazení dle ročníků.

**Comment by LenkaKravecova** [comment]
@zabak Toto už je ok. Když postupuju dle tvého prvního komentu, tak se mi najdou opravdu jen roky 1933-34 a nemusím scrollovat. Můžeme zavřít?

**Comment by zabak** [comment]
Ano, nový klient už má toto vyřešeno včetně řazení a možnosti omezovat roky v rámci periodika, tady není potřeba dál řešit.
