### ISSUE TITLE
kalendář a seznam nefungují pro speciální případy

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#298]
Viz. např. http://www.digitalniknihovna.cz/mzk/periodical/uuid:dce475cb-f3cd-11e0-b9a8-0050569d679d - existuje jen jedno číslo v rámci ročníku (ročenka), bez uvedeného data vydání

**Comment by zabak** [comment]
resp. pro jakékoli ročenky: http://www.digitalniknihovna.cz/mzk/periodical/uuid:e58c6fee-36d7-11e1-959a-0050569d679d

**Comment by honza-rychtar** [comment]
Tohle neni jen jedno cislo v rocniku, ale uplne vynechani urovne cisla a nacpani stranek hned pod rocnik. Digitalni knihovna v techto pripadech umele pridava virtualni cislo. V tomto pripade jsem ale chybne pouzil vychozi zobrazeni pres kalendar. To jsem opravil (bude v dalsi verzi) a zaroven zobrazeni pres kalendar uplne zakazal v pripade, ze rocnik nema ani jedno cislo, ktere ma prirazene datum - coz tyhle rocenky s vynechanym cislem (virtualni cislo datum nema) splnuji, takze v techto pripadech uz nebude zobrazeni pres kalendar vubec nabizeno.

Doporucoval bych, aby se u periodik VZDY pouzivala struktura periodikum -> rocnik -> cislo -> stranka. I kdyz je (dost nestastne) vynechani cisla povolene, tak to neznamena, ze se tahle zkratka musi pouzivat. V pripade K4 klienta to bylo fuk, protoze ten strukturu resil stromem. Ale vsichni novejsi klienti prochazi periodka po urovnich a tyhle zkratky to zbytecne komplikuji. A jen tak mimochodem Android a iOS klienti tyhle rocenky s vynechanym cislem neotevrou vubec.
