### ISSUE TITLE
titleinfo/nonsort - cely nazev v bocnim panelu

### ISSUE THREAD

**Issue by rzeh4n** [honza-rychtar/kramerius-web-client#300]
Když je v MODS něco jako tohle:
```
<titleInfo>
<title>Riesengebirge in Wort und Bild</title>
<nonSort>Das</nonSort>
</titleInfo>
```
Takt to funguje korektně v řazení, protože v solr je 
```
<str name="title_sort">RIESENGEBIRGE IN WORT UND BILD</str>
```
Аle v bočním panelu je jen samtoný title, měl by tam být zřetězený nonsort+mezera+title
Viz
https://www.difmoe.eu/d/periodical/uuid:bec0ac80-a353-4ba7-a7ff-c64dbe2c4dba

**Comment by honza-rychtar** [comment]
Hotovo
