### ISSUE TITLE
zpětná vazba - nevyplněný email

### ISSUE THREAD

**Issue by rzeh4n** [honza-rychtar/kramerius-web-client#308]
Bez vyplnění emailu a kliknutí na odeslat se dialog zpětné vazby zavře. Je to záměr, že se odešle zpráva bez kontaktu na odesílatele? Anebo se jen dialog zavře a nic se neodešle, což není zřejmé?

**Comment by honza-rychtar** [comment]
Povinna je jen zprava. Email neni povinny a zprava se odesle i bez nej. Pokud je vse ok, tak se zprava odesle a dialog zavre.
