### ISSUE TITLE
Chybné zobrazení stránek

### ISSUE THREAD

**Issue by svetlym** [honza-rychtar/kramerius-web-client#309]
U některých dokumentů se nezobrazují celé stránky, viz například:

http://digitalniknihovna.mlp.cz/mlp/view/uuid:ce4e48e4-f14c-4766-85d1-00e0a5778d5c?page=uuid:7f86d3c5-8e5b-11e7-8a09-001b63bd97ba

Ta samá strana ve starém k4 klientu:

http://kramerius4.mlp.cz/search/i.jsp?pid=uuid:7f86d3c5-8e5b-11e7-8a09-001b63bd97ba&q=

Chová se to tak v chromu i firefoxu, jiné prohlížeče jsem nezkoušel.

**Comment by honza-rychtar** [comment]
Tohle uz bylo opraveno ve verzi 0.4.7 (5.4.2017) - http://www.digitalniknihovna.cz/mlp/changelog/
Obrazky se uz zobrazuji spravne:
http://www.digitalniknihovna.cz/mlp/view/uuid:ce4e48e4-f14c-4766-85d1-00e0a5778d5c?page=uuid:7f86d3c5-8e5b-11e7-8a09-001b63bd97ba

Nahraju vam novou verzi klienta, ok?
