### ISSUE TITLE
Lidové noviny únor 1928 - kalendář

### ISSUE THREAD

**Issue by LenkaDamborska** [honza-rychtar/kramerius-web-client#311]
V klientovi se neotvírají únorová čísla ročníku 1928 Lidových novin, když je otvírám z kalendářového zobrazení. Místo toho se zobrazí březnová čísla (v únoru i v březnu, takže jsou tam jakoby dvakrát). Když si přepnu prohlížení čísel na seznam nebo karty, tak už se mi únorová čísla zobrazí. V Krameriu se únorová čísla zdají být v pořádku. Bude problém asi s tím kalendářovým zobrazením.

**Comment by honza-rychtar** [comment]
Tohle je bug, ktery se projevuje vzdy 31. v mesici :) Uz jsem to opravil, jen jsem to jeste neaktualizoval na www.digitalniknihovna.cz

**Comment by LenkaDamborska** [comment]
Ještě to není aktualizované, že? Píše mi další uživatel, že chce noviny z 13.2.1943 a ukazuje se mu březen.

**Comment by LenkaDamborska** [comment]
Mám další hlášení od jiného člověka. Jinak projevuje se to i 30. den v měsíci. Psali včera.

**Comment by honza-rychtar** [comment]
Aktualizovane to bylo, ale konkretne tenhle bug se dal projevoval v produkcni verzi (kvuli ruznym verzim externich knihoven).
Opravil jsem to a vydal novou verzi, ted uz to bude fungovat.

**Comment by LenkaDamborska** [comment]
Moc díky. Včera psal ještě někdo třetí. Tak aspoň víme, že se DK používá :)
