### ISSUE TITLE
Nemožnost vygenerovat PDF při dvoustránkovém zobrazení

### ISSUE THREAD

**Issue by LenkaKravecova** [honza-rychtar/kramerius-web-client#312]
Pokud mám zapnuto dvoustránkové zobrazení a chci stáhnout do PDF určitý rozsah stran (ne jen jednu), nelze vygenerovat PDF. Hlásí to "PDF dokument se nepodařilo vytvořit."

**Comment by honza-rychtar** [comment]
Posli mi nejaky priklad - dokument, aktivni stranky, vybrane stranky pro generovani.
Tohly by urcite fungovat melo.

**Comment by LenkaDamborska** [comment]
Teď se mi to stalo dvakrát tady http://www.digitalniknihovna.cz/mzk/view/uuid:66f3d667-6e6b-4271-b1e1-2f6688b840c2?page=uuid:0394bba2-687f-48ea-b419-5e570940708a, ale pak dvakrát to zas šlo, tak nevím.. Před tím jsem to zkoušela v jiné knížce, kde se mi to taky stalo dvakrát, ale teď to zas šlo :) Tak možná jen planý poplach

**Comment by LenkaKravecova** [comment]
Nevím, proč to nešlo, ale už se mi to nestalo, takže zavírám.
