### ISSUE TITLE
Nevalidní URL do SOLRu

### ISSUE THREAD

**Issue by MartinRumanek** [honza-rychtar/kramerius-web-client#313]
@dsecik a @kenji1322 mi hlásili, že s novým releasem Krameria 5.4.0 nefunguje vyhledávání v digitální knihovně.
Neudělali jsme to schválně, ale Kramerius 5.4.0 je striktnější co se týče URL dotazů do SOLRu (muselo se to stát kvůli aktualizaci nějaké knihovny). 
_________
 Caret (^) který v URL posíláš, nemá v query co dělat, je to nevalidní znak, měl bys ho enkódovat jako další speciální znaky. 

V Krameriu to teď opravím (snad), ale pozor na to prosím. Příště to může být problém jinde. Např. nový Tomcat nepustí do URL znaky {}.

**Comment by honza-rychtar** [comment]
@MartinRumanek Ok, caret encoduju.
