### ISSUE TITLE
velikost hlavicky / horniho radku na uvodni obrazovce

### ISSUE THREAD

**Issue by filipsir** [honza-rychtar/kramerius-web-client#317]
byla by moznost toto schovavat? ci udelat mensi? 

a) na hlavni strane kde je to doopravdy zbytecne velke - prostor je nevuzit tak jak ma byt - lista sbirky-prochazet-english. idealne schovavat ci mensi.
https://www.dropbox.com/s/p7ah0m8j8l4depx/Screenshot%202018-03-20%2014.58.33.png?dl=0

oproti tomu:
b) prostor s logem vetsi, vic rikajici o instituci - prostor od loga k horni liste zbytecne velky

**Comment by honza-rychtar** [comment]
Tohle patri sem https://github.com/ceskaexpedice/kramerius-web-client/issues
