### ISSUE TITLE
analytics a sledování jestli navštívená stránka byla volná nebo ne

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#318]
Dá se z analytics nějak vyčíst jestli byla zobrazena stránka dokumentu, nebo jen hláška o autorských právech? Tj. kolik bylo pokusů obrazit si chráněný dokument?

**Comment by honza-rychtar** [comment]
Ne, ale mohl bych to pridat. Ted se neodesilaji stranky vubec, jen dokument, tj. jen prvni otevrena stranka.
