### ISSUE TITLE
GA - sběr dat o stahování pdf

### ISSUE THREAD

**Issue by svetlym** [honza-rychtar/kramerius-web-client#321]
Dobrý den,

potřebovali bychom sledovat statistiku stahování pdfek přes klienta Kraméria. Bylo by možné tuto informaci posílat do GA?

**Comment by honza-rychtar** [comment]
Stahovani PDF se (uz dlouho) posila pres udalosti.

1) Uzivatel klikl v toolbaru na Stahnout jako PDF
Udalost: Toolbar -> Download -> PDF

2) Uzivatel klikl v toolbatu na Priprava k tisku
Udalost: Toolbar -> Download -> Print

3) Uzivalte v dialogu Generovni PDF nebo Priprava k tisku klikl na zrusit
Udalsot: PDF -> Cancel -> [URL_DOKUMENTU]

4) Uzivalte v dialogu Generovni PDF klikl na Generovat
Udalsot: PDF -> Download -> [URL_DOKUMENTU]

5) Uzivalte v dialogu Priprava k tisku klikl na Pripravit k tisku
Udalsot: PDF -> Print -> [URL_DOKUMENTU]

Takze pocet stazenych PDF ziskate pres 4). K tomu asi bude chtit pricist 5) - otevreni pdf v novem tabu.

**Comment by svetlym** [comment]
Díky za upřesnění. Předal jsem informace dál a vypadá to, že to splňuje požadovanou funkčnost.
