### ISSUE TITLE
Periodikum Neuigkeiten - nezobrazují se některá čísla

### ISSUE THREAD

**Issue by LenkaKravecova** [honza-rychtar/kramerius-web-client#326]
Jde o ročník 1857 uuid:8a2df1b0-0cb9-11e8-bdb0-005056827e51. Nezobrazují se čísla 98 - 118 (skoro celý duben). V Krameriu čísla jsou. Na digitalniknihovna.cz se k nim dá proklikat přes funkci v prohlížečce Předchozí číslo, Následující číslo, ale nezobrazí se v kalendáři, ani v seznamu čísel.
V novém klientovi nejsou vůbec.

**Comment by honza-rychtar** [comment]
Maji v datu vyplneny kveten misto dubna. V kalendari skoci do kvetna a v zobrazeni mrizkou jsou zamichane az v kvetnu.
Napr. http://www.digitalniknihovna.cz/mzk/view/uuid:4883a190-0d24-11e8-bdb0-005056827e51?page=uuid:92100750-0d32-11e8-8ee4-005056825209
10.**05**.1857

**Comment by LenkaKravecova** [comment]
Jo aha, tak to jsem si nevšimla, datum jsem nezkoumala. Tak potom je to jasné :) Nechám opravit.
