### ISSUE TITLE
Digitální knihovna přes https

### ISSUE THREAD

**Issue by xRahman** [honza-rychtar/kramerius-web-client#327]
Dobrý den,

rádi bychom přepnuli klienta na https, zejména kvůli tomu, že Google teď začíná downrankovat stránky, které stále běží přes http.

Myslel jsem si, že to bude čistě záležitost serveru, ale není to tak. Dotazy na K5 api jsou totiž přes http protokol, takže je browser v https módu zakáže:

```
vendor-0.6.2.min.js:130 Mixed Content: The page at 
'https://digitalniknihovna.mlp.cz/mlp/' was loaded over HTTPS, but 
requested an insecure XMLHttpRequest endpoint 
'http://kramerius4.mlp.cz/search/api/v5.0/info'. This request has been 
blocked; the content must be served over HTTPS.
```

Na K5 serveru jsme https zapnuli taky, takže https://kramerius4.mlp.cz/search/api/v5.0/info v pohodě projde - jen musí klient vygenerovat dotaz v tomhle formátu.

Šlo by na to udělat přepínač v nastavení, nebo něco v tom smyslu? (Respektive pokud klient pozná, že běží přes https, tak by se to ideálně mohlo dít automaticky).

**Comment by honza-rychtar** [comment]
V kořenové složce s klientem je konfigurační soubor /config/config.js, kde stačí změnit v libraries -> url 'http://kramerius4.mlp.cz/' na 'https://kramerius4.mlp.cz/'

**Comment by xRahman** [comment]
Funguje, díky :)
