### ISSUE TITLE
vyhledávání - v okýnku by při změně kontextu mohl zůstat vyhledávaný text

### ISSUE THREAD

**Issue by pavluska** [honza-rychtar/kramerius-web-client#39]
v horní liště něco vyhledávám - pominu, že hledat ve všem i evokuje i hledat ve fulltextu - takže něco napíšu, vyhledám, nic mi to nenajde, uvědomím si, že nehledám ve fulltextu, přepnu se na fulltext a hledaný výraz musím napsat znovu, jsem trochu naštvaná... bylo by moc krásné, kdyby tam hledaný výraz zůstal

**Comment by zabak** [comment]
Bylo by krásné, kdyby fungovala relevance. Zadám výraz, na prvních místech budou hity z metadat, za tím hity z fulltextu. Nemusím dávat dvakrát vyhledávací dotaz.

**Comment by pavluska** [comment]
to si podle me zaslouzi zvlastni issue, tak jsem to nepsala :) ale Honza uz
si ho tam mozna zadal sam, protoze jsem mu to uz rikala...

po 13. 4. 2015 v 22:39 odesílatel zabak <notifications@github.com> napsal:
