### ISSUE TITLE
Procházení podle typu a návrat zpět

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#42]
Pokud kliknu na procházení podle typu a pak třeba rukopisy a pak nějaký rukopis, tak šipka zpět, která se objeví vlevo nahoře místo aby mě vrátila do seznamu rukopisů mě vrátí na hlavní stránku.

**Comment by LenkaDamborska** [comment]
Jak se toto vyřešilo? @zabak má podobnou připomínku, vkládám sem:
pokud jdeš do periodika na konkrétní číslo, tak  se z toho čísla vrátíš šipkou v horním rohu na seznam čísel v rámci ročníku, ale další klik na šipku tě hodí na začátek a ne na seznam ročníků
