### ISSUE TITLE
procházení dle klíčových slov - nevhodné zobrazení

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#43]
vícesloupcové zobrazení je pro tento typ seznamu nevhodné, lepší by bylo mít jeden sloupec a "nízké" řádky. Navíc by místo řazení dle četnosti bylo lepší abecední řazení.

**Comment by honza-rychtar** [comment]
S radky souhlasim.
Abecedni razeni by spis davalo smysl u vyhledavani - tohle je prochazeni. Spis chci zjistit co knihovna vubec obsahuje. Pokud by tam bylo hodne klicovych slov, tak bych musel projit pres spoustu nesmyslu zacinajici na a,b,c, ktere obsahuji jen jeden dokument.
