### ISSUE TITLE
Rozcestník pro zobrazení metadat

### ISSUE THREAD

**Issue by jirduf** [honza-rychtar/kramerius-web-client#46]
Různé formáty by měly mít alespoň nadpis pro celek i pro sloupce (česky). Např. "Dostupná metadata" + sloupce: "K celému číslu" a "K aktuální straně".
jd
![metadata_issue](https://cloud.githubusercontent.com/assets/3939406/7292739/abb12de8-e99e-11e4-9914-f90e93a01085.jpg)

**Comment by honza-rychtar** [comment]
Tohle je urceno jen pro vyvoj. V ostre verzi tenhle dialog vypnu. Misto nej bude sdileni dokumentu na Facebooku Google+, Twitteru, ...
