### ISSUE TITLE
search inside - a návrat do dokumentu

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#47]
Když dám hledat nějaké slovo, vyberu si relevantní stránku a chci číst stránku následující (co už dané slovo neobsahuje), musím zrušit vyhledávací dotaz. V tom okamžiku ale systém skočí na začátek dokumentu, nezůstane na stránce na které jsem předtím byl.

**Comment by honza-rychtar** [comment]
Opraveno
