### ISSUE TITLE
posuvník veřejné / neveřejné - pochopitelnost

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#51]
Pořád se mi nelíbí to jak je označen posuvník veřejné / neveřejné. Kdyby to bylo zatržítko, tak vím že pokud je zatržené tak platí text vedle něj, ale u toho posuvníku to tak jasné není, protože není jasné jaká poloha je zapnuto a jaká vypnuto. Ideální by bylo, kdyby byly popsané obě polohy: zobrazit vše - zobrazit veřejné.

**Comment by LenkaDamborska** [comment]
S tímto souhlasím. Dnes jsem něco hledala a zjistila jsem, že mě to vlastně taky mate. Takže něco jako zobrazit vše - pouze veřejné by se hodilo.

**Comment by honza-rychtar** [comment]
Prepinatko se zrusi
Viz #137
