### ISSUE TITLE
zobrazení více autorů v novinkách

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#54]
Když má kniha více autorů, zobrazují se na kartách bez mezery, je to vidět v novinkách. Navíc se zobrazí jen omezený počet autorů na jeden řádek, ale dost často je tam něco jako "Matuška, WaldemarRokl," a chybí křestní jméno druhého autora přesto, že je tam ještě na řádku místo.

**Comment by honza-rychtar** [comment]
To uz jsme resili nekolikrat. Problem je v API u feedu custom a newest.
Takto vypada dotaz na novinky - http://kramerius.mzk.cz/search/api/v5.0/feed/newest/
"author":["Smoljak, LadislavCimrman, Jára daSvěrák, ZdeněkDivadlo Járy Cimrmana"]
V poli author jsou vsichni autori zretezeni do jednoho retezce bez mezer.
Spravne to ma byt:
"author":["Smoljak, Ladislav", "Cimrman, Jára da", "Svěrák, Zdeněk", "Divadlo Járy Cimrmana"]

Ostatni knihovny (napr. KNAV a Olomouc) maji stejny problem.
Ale je zajimave, ze u NDK to funguje spravne:
http://krameriusndktest.mzk.cz/search/api/v5.0/feed/newest/

**Comment by honza-rychtar** [comment]
Problem API - https://github.com/moravianlibrary/kramerius/issues/10
