### ISSUE TITLE
změna krameria vs. hledání

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#55]
když zadám vyhledávací dotaz a po zobrazení výsledků přepnu na jiného Krameria, zachová se mi sice dotaz ve vyhledávacím okénku, ale vyhledání se znovu neprovede, musí se ručně odpálit. Přitom ale se nedá odpálit kliknutím na lupičku před vyhledávacím dotazem.

**Comment by honza-rychtar** [comment]
Puvodne to bylo tak, ze po zmene Krameria se reloadnula stranka 9at uz jsem byl kdekoli), takze u hledani se vysledky nacetly znova pro nove vybraneho Krameria.

Jenze pokud jsem byl treba na obrazovce nastaveni a zmenil jsem Krameria, pak se nic nestalo a pro uzivatele to budilo dojem, ze zadna zmena neprobehla, tak jsem to zmenil, at se po zmene Krameria prejde na hlavni stranku, tj doporucene.

U hledani byl vyhodny ten predchozi pristup, protoze muzu zadat hledany text jen jednou a pak menit Krameria a hned vidim vysledky v nem.

Obrazovka s vysledky hledani se bude menit - misto hlavniho menu bude panel s dodatecnyma volbama hledani - facety, filtry, trideni, zobrazeni poctu nalezenych apod.
Takze tam stejne moznost prepnout Krameria nebude.
