### ISSUE TITLE
prý to vůbec nefunguje v safari na iosu (prosím otestovat na ipadu)

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#58]

**Comment by black23** [comment]
Na ios 8 a iPhone nelze reálně otevřít téměř nic. Menu se vysunuje, ale nezobrazí, na náhledy jde kliknout, ale dál se načtou jen metadata. Můžu otestovat víc, pokud dostanu konrétní zadání.
![img_1996](https://cloud.githubusercontent.com/assets/5516936/8801658/8fcc7d6c-2fbc-11e5-98cf-a72f8d718133.jpg)
![img_1995](https://cloud.githubusercontent.com/assets/5516936/8801660/8fd05798-2fbc-11e5-8818-ebb9b9bf2423.jpg)
![img_1994](https://cloud.githubusercontent.com/assets/5516936/8801659/8fcda43a-2fbc-11e5-94ce-9115cbc1878b.jpg)
