### ISSUE TITLE
prohlížení vyhledaných dokumentů

### ISSUE THREAD

**Issue by zabak** [honza-rychtar/kramerius-web-client#78]
Od Karolíny: "Když hledám v plném textu, najde mi to stránku, tu si otevřu (trefila jsem se třeba do Pestrého týdne) a chtěla bych si prolistovat nejen tu stránku, kde se našlo slovo, ale celé číslo. Jak to mám udělat? Mám sice šipky na listování, ale to se pohybuju jen mezi stránkami, kde se našlo hledané slovo. Škoda, že už pak u konkrétní stránky u periodik není vytažené, které konkrétní číslo to je, je tam jen obecný záznam periodika. Omlouvám se, jinak je to pěkné :)"

**Comment by honza-rychtar** [comment]
Krizkem u hledani v dokumentu se zrusi fulltext a zobrazi se vsechny stranky.
Tady je chyba, ze po zruseni fulltextu prejde na prvni stranku, mela by zustat otevrena prave prohlizena stranka #47

Informace o cisle a rocniku budou doplneny #80
