### ISSUE TITLE
Chyba ve Firefoxu

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#88]
Od verze 0.0.6 aplikace pada ve Firefoxu (jen nekomu).

**Comment by black23** [comment]
Potrzuji zasekávání na skriptu Angular v Firefox v 39.0 na OS X. Ale pouze na jednom počítači. Na dalších, kde je stejný OS i FF je to ok. Možná kolize z nějakým doplňkem?
