### ISSUE TITLE
Doplnujici informace v nahledu stranek v prohlizecce.

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#89]
Zobrazit u kazdeho thumbnailu cislo stranky.
Dal potom typ stranky - ten se tam ale uplne nevejde, asi by stacilo zobrazovat jen ikonu pro vybrane typy - napr. reklama. 
Predpokladam, ze napr. typ "Predni strana" uzivatele nezajima, staci kdyz pri vyberu teto stranky se typ vypise vpravo do metadat.
Takze by pres thumbnail byla ikona reprezentujici typ stranky a cislo stranky.

Klidne muzeme rozlisit ikonou vsechny typy stranek, ale to bude graficky orisek - udelat malicke a dostatecne odlisne ikony pro predni/zadni/prazdnou/normalni stranky.
Myslim, ze by stacilo rozlisit reklamu od normalni stranky.

**Comment by black23** [comment]
Z toho, co je předdefinované v Krameriu a používáme jsou zajímavé asi jen "reklama" a "tabulka". Co zkusit zobrazit slovní popis nebo ikonu po přidržení nad náhledem? Tak by bylo možné se ještě před klikem rozhodnou jestli to chci opravdu ukázat a zároveň by to ve výchozím zobrazení nijak nesnižovalo "čitelnost" náhledu.

**Comment by honza-rychtar** [comment]
Udelal jsem to teda tak, ze u kazdeho nahledu je cislo stranky a po najeti mysi na nahled se pres jeho spodni cast vypise typ stranky.

Cislo i typ stranky jsem pridal i do vypisu metadat.

Zatim mapuju tyhle typy stranek:
    "frontcover": "přední desky",   
    "frontendsheet": "přední přídeští",   
    "backcover": "zadní desky",
    "backendsheet": "zadní přídeští",   
    "cover": "desky",
    "blank": "prázdná strana",   
    "normalpage": "strana",
    "advertisement": "reklama",
    "titlepage": "titulní strana",
    "tableofcontents": "obsah",
    "map": "mapa",
    "index": "rejstřík",
    "frontjacket": "obálka",
    "jacket": "obálka",
    "listofillustrations": "seznam ilustrací",
    "flyleaf" : "volný list",
    "spine" : "hřbet"

Vse ostatni vypisu jako "strana".
Doplnte nekdo prosim zbyvajici typy. 
Nejllepe dva seznamy - CS a EN
