### ISSUE TITLE
Zobrazit informace o vybranem Krameriovi

### ISSUE THREAD

**Issue by honza-rychtar** [honza-rychtar/kramerius-web-client#90]
Intro pres API - http://k5.digiknihovna.cz/search/api/v5.0/info

Problem je, ze vyplnene informace se zobrazuji i v jinych klientech a muze tam byt popis a linky, ktere se netykaji tohoto klienta.

**Comment by black23** [comment]
Co vlastní editovatelný text přímo pro klienta. Třeba i jako druhá možnost. Výchozí nastavení by bylo přebrat z Krameria, druhá vytvořit si vlastní popisek.

**Comment by honza-rychtar** [comment]
Udelal jsem to tak, ze pro kazdou instanci klienta se v konfiguraci nastavi jestli se ma pouzit intro text (editovatelny v administracnim rozhrani Krameria) nebo se pouzije defautni info (info o aplikaci samotne).

Takze v klientovi u me, kde je na vyber z vice Krameriu to v konfiguraci zakazu a pouzije se jednoty informacni text.
U klientu pro konkretni instituci se pak instituce vybere jestli chce zobrazovat intro text (ktery muze konfigurovat nezavisle na klientovi).
