### ISSUE TITLE
Výraz fulltext, hledat ve fulltextu

### ISSUE THREAD

**Issue by black23** [honza-rychtar/kramerius-web-client#94]
Navrhuji zvážit změnu na Hledat v textu. Běžný člověk nemusí nutně tušit, co je to fulltext a dokonce ani co je plný text.

**Comment by honza-rychtar** [comment]
Do vysledku zakladniho hledani pridam na konec i vysledky fulltextoveho hledani #64 
Takze uzivatel nebude muset primo vybirat fulltext a ani vedet co to je.

**Comment by black23** [comment]
Tak je to ideální :-)
