### ISSUE TITLE
Možnost vložit javascript pro analytiku

### ISSUE THREAD

**Issue by black23** [honza-rychtar/kramerius-web-client#95]
Hodila by se nám možnost vložit skript pro vyhodnocování provozu a chování uživatelů (GA, Piwik atd.).

**Comment by honza-rychtar** [comment]
GA Analytics tam je. Je to soucasti konfiguracniho souboru klienta, kde se nastavuji veci jako seznam krameriu pristupnych v klientovi, defaultni kramerius, pouziti vlastni textu v informacich, zobrazeni vyvojarskych nastroju, GA tracker ID apod.

V tuhle chvili je klient nasazeny 4x a kazdy ma vlastni Tracker ID.
Muzu tam dat tracker id, ktery vytvorite v GA pod svym uctem. V tom pripade prosim o pristup k uctu (resp. jen k teto konkretni sluzbe), at aspon jeste v teto fazi vyvoje vidim, ze to funguje spravne.
Nebo naopak ja dam vam pristup ke sluzbe do meho GA.

To stejne plati pro MZK. Nez se bude klient pouzivat produkcne, tak to zmenim na GA od MZK.

Pozdeji tam pridam co nejvic vhodnych udalosti, ktere nam reknou jakym zpusobem uzivatele klienta pouzvaji. Jako napr. jestli lidi generuji pdf casteji jen z vybrane stranky nebo z vice stranek, pripadne cele dokumenty, jake jsou nejcastejsi kriteria vyhledavani apod.
